! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Jacobian Data Structures File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : model_JacobianSP.f90
! Time                 : Sat Apr 22 13:43:50 2017
! Working directory    : /work/home/dp626/DSMACC-testing
! Equation file        : model.kpp
! Output root filename : model
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE model_JacobianSP

  PUBLIC
  SAVE


! Sparse Jacobian Data


  INTEGER, PARAMETER, DIMENSION(177) :: LU_IROW = (/ &
       1,  1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  4, & ! index 1 - 12
       4,  4,  5,  5,  6,  6,  6,  7,  7,  7,  8,  8, & ! index 13 - 24
       8,  9,  9,  9, 10, 10, 10, 11, 11, 11, 12, 12, & ! index 25 - 36
      12, 13, 13, 13, 13, 14, 14, 14, 15, 15, 15, 15, & ! index 37 - 48
      16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 18, 18, & ! index 49 - 60
      18, 18, 18, 19, 19, 19, 19, 20, 20, 20, 20, 20, & ! index 61 - 72
      20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, & ! index 73 - 84
      21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, & ! index 85 - 96
      22, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, & ! index 97 - 108
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, & ! index 109 - 120
      24, 24, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25, & ! index 121 - 132
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, & ! index 133 - 144
      26, 26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, & ! index 145 - 156
      27, 27, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, & ! index 157 - 168
      28, 28, 28, 28, 28, 28, 28, 28, 28 /)

  INTEGER, PARAMETER, DIMENSION(177) :: LU_ICOL = (/ &
       1, 23, 24, 27, 28,  2,  6, 14, 23,  3,  4,  3, & ! index 1 - 12
       4, 24,  5, 27,  6, 14, 24,  7, 21, 25,  8, 20, & ! index 13 - 24
      24,  9, 22, 25, 10, 24, 28, 11, 21, 24, 12, 24, & ! index 25 - 36
      26, 13, 20, 22, 24, 14, 23, 24, 15, 24, 25, 28, & ! index 37 - 48
      16, 17, 19, 21, 22, 26, 17, 21, 24, 26, 18, 20, & ! index 49 - 60
      22, 24, 25, 19, 21, 24, 28, 11, 16, 17, 19, 20, & ! index 61 - 72
      21, 22, 24, 26, 28,  3,  4,  7, 19, 21, 22, 24, & ! index 73 - 84
      25, 26, 28,  9, 18, 20, 21, 22, 23, 24, 25, 26, & ! index 85 - 96
      27, 28,  5, 14, 22, 23, 24, 25, 26, 27, 28,  4, & ! index 97 - 108
       5,  8, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, & ! index 109 - 120
      21, 22, 23, 24, 25, 26, 27, 28,  7,  9, 12, 15, & ! index 121 - 132
      17, 18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 12, & ! index 133 - 144
      21, 22, 23, 24, 25, 26, 27, 28, 23, 24, 25, 26, & ! index 145 - 156
      27, 28,  6,  8, 10, 11, 13, 14, 15, 16, 17, 19, & ! index 157 - 168
      20, 21, 22, 23, 24, 25, 26, 27, 28 /)

  INTEGER, PARAMETER, DIMENSION(29) :: LU_CROW = (/ &
       1,  6, 10, 12, 15, 17, 20, 23, 26, 29, 32, 35, & ! index 1 - 12
      38, 42, 45, 49, 55, 59, 64, 68, 78, 88, 99,108, & ! index 13 - 24
     129,144,153,159,178 /)

  INTEGER, PARAMETER, DIMENSION(29) :: LU_DIAG = (/ &
       1,  6, 10, 13, 15, 17, 20, 23, 26, 29, 32, 35, & ! index 1 - 12
      38, 42, 45, 49, 55, 59, 64, 72, 82, 92,102,124, & ! index 13 - 24
     140,150,157,177,178 /)


END MODULE model_JacobianSP

