! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : model_Monitor.f90
! Time                 : Thu Feb 16 17:13:46 2017
! Working directory    : /work/home/dp626/DSMACC-testing
! Equation file        : model.kpp
! Output root filename : model
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE model_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(48) :: SPC_NAMES = (/ &
     'DUMMY          ','SA             ','SO3            ', & ! index 1 - 3
     'O1D            ','HSO3           ','N2O5           ', & ! index 4 - 6
     'H2             ','CH3OH          ','HNO3           ', & ! index 7 - 9
     'HCOOH          ','HONO           ','SO2            ', & ! index 10 - 12
     'HO2NO2         ','RU14NO3        ','CH3CO3H        ', & ! index 13 - 15
     'H2O2           ','RU10OOH        ','C5H8           ', & ! index 16 - 18
     'RU12PAN        ','HOCH2CO3H      ','CH3NO3         ', & ! index 19 - 21
     'CH3OOH         ','RU12OOH        ','MPAN           ', & ! index 22 - 24
     'PHAN           ','PAN            ','RU14OOH        ', & ! index 25 - 27
     'CH3O2          ','CARB7          ','CO             ', & ! index 28 - 30
     'HCHO           ','HOCH2CO3       ','RU14O2         ', & ! index 31 - 33
     'CARB6          ','UCARB12        ','HOCH2CHO       ', & ! index 34 - 36
     'RU10O2         ','CH3CO3         ','RU12O2         ', & ! index 37 - 39
     'UCARB10        ','O              ','NO2            ', & ! index 40 - 42
     'OH             ','HO2            ','O3             ', & ! index 43 - 45
     'NO3            ','NO             ','EMISS          ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '             O --> O3                                                                               ', & ! index 1
     '        O + O3 --> DUMMY                                                                            ', & ! index 2
     '        O + NO --> NO2                                                                              ', & ! index 3
     '       O + NO2 --> NO                                                                               ', & ! index 4
     '       O + NO2 --> NO3                                                                              ', & ! index 5
     '           O1D --> O                                                                                ', & ! index 6
     '       O3 + NO --> NO2                                                                              ', & ! index 7
     '      NO2 + O3 --> NO3                                                                              ', & ! index 8
     '          2 NO --> 2 NO2                                                                            ', & ! index 9
     '      NO3 + NO --> 2 NO2                                                                            ', & ! index 10
     '     NO2 + NO3 --> NO2 + NO                                                                         ', & ! index 11
     '     NO2 + NO3 --> N2O5                                                                             ', & ! index 12
     '          N2O5 --> NO2 + NO3                                                                        ', & ! index 13
     '           O1D --> 2 OH                                                                             ', & ! index 14
     '       OH + O3 --> HO2                                                                              ', & ! index 15
     '       H2 + OH --> HO2                                                                              ', & ! index 16
     '       CO + OH --> HO2                                                                              ', & ! index 17
     '     H2O2 + OH --> HO2                                                                              ', & ! index 18
     '      HO2 + O3 --> OH                                                                               ', & ! index 19
     '      OH + HO2 --> DUMMY                                                                            ', & ! index 20
     '         2 HO2 --> H2O2                                                                             ', & ! index 21
     '       OH + NO --> HONO                                                                             ', & ! index 22
     '      NO2 + OH --> HNO3                                                                             ', & ! index 23
     '      OH + NO3 --> NO2 + HO2                                                                        ', & ! index 24
     '      HO2 + NO --> NO2 + OH                                                                         ', & ! index 25
     '     NO2 + HO2 --> HO2NO2                                                                           ', & ! index 26
     '        HO2NO2 --> NO2 + HO2                                                                        ', & ! index 27
     '   HO2NO2 + OH --> NO2                                                                              ', & ! index 28
     '     HO2 + NO3 --> NO2 + OH                                                                         ', & ! index 29
     '     HONO + OH --> NO2                                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '     HNO3 + OH --> NO3                                                                              ', & ! index 31
     '       SO2 + O --> SO3                                                                              ', & ! index 32
     '      SO2 + OH --> HSO3                                                                             ', & ! index 33
     '          HSO3 --> SO3 + HO2                                                                        ', & ! index 34
     '            O3 --> O1D                                                                              ', & ! index 35
     '            O3 --> O                                                                                ', & ! index 36
     '          H2O2 --> 2 OH                                                                             ', & ! index 37
     '           NO2 --> O + NO                                                                           ', & ! index 38
     '           NO3 --> NO                                                                               ', & ! index 39
     '           NO3 --> O + NO2                                                                          ', & ! index 40
     '          HONO --> OH + NO                                                                          ', & ! index 41
     '          HNO3 --> NO2 + OH                                                                         ', & ! index 42
     '           SO3 --> SA                                                                               ', & ! index 43
     '         DUMMY --> 0.5 DUMMY                                                                        ', & ! index 44
     '         EMISS --> EMISS                                                                            ', & ! index 45
     '    CH3OH + OH --> HCHO + HO2                                                                       ', & ! index 46
     '          HCHO --> H2 + CO                                                                          ', & ! index 47
     '     HCHO + OH --> CO + HO2                                                                         ', & ! index 48
     '          HCHO --> CO + 2 HO2                                                                       ', & ! index 49
     '     C5H8 + OH --> RU14O2                                                                           ', & ! index 50
     '     C5H8 + O3 --> CO + UCARB10 + OH + HO2                                                          ', & ! index 51
     '     C5H8 + O3 --> HCOOH + UCARB10                                                                  ', & ! index 52
     '    HCOOH + OH --> HO2                                                                              ', & ! index 53
     '        CH3CO3 --> CH3O2                                                                            ', & ! index 54
     '  CH3CO3 + NO2 --> PAN                                                                              ', & ! index 55
     '  CH3CO3 + HO2 --> CH3CO3H                                                                          ', & ! index 56
     '   CH3CO3 + NO --> CH3O2 + NO2                                                                      ', & ! index 57
     '         CH3O2 --> CH3OH                                                                            ', & ! index 58
     '    CH3O2 + NO --> CH3NO3                                                                           ', & ! index 59
     '         CH3O2 --> HCHO                                                                             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '         CH3O2 --> HCHO + HO2                                                                       ', & ! index 61
     '   CH3O2 + HO2 --> CH3OOH                                                                           ', & ! index 62
     '    CH3O2 + NO --> HCHO + NO2 + HO2                                                                 ', & ! index 63
     '   RU14O2 + NO --> RU14NO3                                                                          ', & ! index 64
     '  RU14O2 + HO2 --> RU14OOH                                                                          ', & ! index 65
     '        RU14O2 --> UCARB12 + HO2                                                                    ', & ! index 66
     '   RU14O2 + NO --> UCARB12 + NO2 + HO2                                                              ', & ! index 67
     '        RU14O2 --> HCHO + UCARB10 + HO2                                                             ', & ! index 68
     '   RU14O2 + NO --> HCHO + UCARB10 + NO2 + HO2                                                       ', & ! index 69
     '  UCARB10 + OH --> RU10O2                                                                           ', & ! index 70
     '  UCARB10 + O3 --> CO + HCHO + CH3CO3 + OH                                                          ', & ! index 71
     '       UCARB10 --> HCHO + CH3CO3 + HO2                                                              ', & ! index 72
     '  UCARB10 + O3 --> H2O2 + HCHO + CARB6                                                              ', & ! index 73
     ' HOCH2CHO + OH --> HOCH2CO3                                                                         ', & ! index 74
     '      HOCH2CHO --> CO + HCHO + 2 HO2                                                                ', & ! index 75
     '           PAN --> CH3CO3 + NO2                                                                     ', & ! index 76
     '      PAN + OH --> CO + HCHO + NO2                                                                  ', & ! index 77
     '       CH3CO3H --> CH3O2 + OH                                                                       ', & ! index 78
     '  CH3CO3H + OH --> CH3CO3                                                                           ', & ! index 79
     '   CH3NO3 + OH --> HCHO + NO2                                                                       ', & ! index 80
     '        CH3NO3 --> HCHO + NO2 + HO2                                                                 ', & ! index 81
     '   CH3OOH + OH --> CH3O2                                                                            ', & ! index 82
     '   CH3OOH + OH --> HCHO + OH                                                                        ', & ! index 83
     '        CH3OOH --> HCHO + OH + HO2                                                                  ', & ! index 84
     '    CARB6 + OH --> CO + CH3CO3                                                                      ', & ! index 85
     '         CARB6 --> CO + CH3CO3 + HO2                                                                ', & ! index 86
     '  RU14NO3 + OH --> UCARB12 + NO2                                                                    ', & ! index 87
     '  RU14OOH + OH --> UCARB12 + OH                                                                     ', & ! index 88
     '       RU14OOH --> UCARB12 + OH + HO2                                                               ', & ! index 89
     '       RU14OOH --> HCHO + UCARB10 + OH + HO2                                                        ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '  UCARB12 + OH --> RU12O2                                                                           ', & ! index 91
     '  UCARB12 + O3 --> CO + HOCH2CHO + CH3CO3 + OH                                                      ', & ! index 92
     '  UCARB12 + O3 --> H2O2 + CARB6 + HOCH2CHO                                                          ', & ! index 93
     '       UCARB12 --> CO + HOCH2CHO + CH3CO3 + HO2                                                     ', & ! index 94
     '  RU10O2 + NO2 --> MPAN                                                                             ', & ! index 95
     '        RU10O2 --> HOCH2CHO + CH3CO3                                                                ', & ! index 96
     '  RU10O2 + HO2 --> RU10OOH                                                                          ', & ! index 97
     '        RU10O2 --> HCHO + CARB6 + HO2                                                               ', & ! index 98
     '        RU10O2 --> CARB7 + HCHO + HO2                                                               ', & ! index 99
     '   RU10O2 + NO --> HOCH2CHO + CH3CO3 + NO2                                                          ', & ! index 100
     '   RU10O2 + NO --> CARB7 + HCHO + NO2 + HO2                                                         ', & ! index 101
     '   RU10O2 + NO --> HCHO + CARB6 + NO2 + HO2                                                         ', & ! index 102
     'HOCH2CO3 + HO2 --> HOCH2CO3H                                                                        ', & ! index 103
     '      HOCH2CO3 --> HCHO + HO2                                                                       ', & ! index 104
     'HOCH2CO3 + NO2 --> PHAN                                                                             ', & ! index 105
     ' HOCH2CO3 + NO --> HCHO + NO2 + HO2                                                                 ', & ! index 106
     '    CARB7 + OH --> CARB6 + HO2                                                                      ', & ! index 107
     '         CARB7 --> HCHO + CH3CO3 + HO2                                                              ', & ! index 108
     '  RU12O2 + NO2 --> RU12PAN                                                                          ', & ! index 109
     '  RU12O2 + HO2 --> RU12OOH                                                                          ', & ! index 110
     '        RU12O2 --> HOCH2CHO + CH3CO3                                                                ', & ! index 111
     '        RU12O2 --> CARB7 + HOCH2CHO + HO2                                                           ', & ! index 112
     '   RU12O2 + NO --> CARB7 + CO + NO2 + HO2                                                           ', & ! index 113
     '   RU12O2 + NO --> HOCH2CHO + CH3CO3 + NO2                                                          ', & ! index 114
     '          MPAN --> RU10O2 + NO2                                                                     ', & ! index 115
     '     MPAN + OH --> CARB7 + CO + NO2                                                                 ', & ! index 116
     '  RU10OOH + OH --> RU10O2                                                                           ', & ! index 117
     '       RU10OOH --> HOCH2CHO + CH3CO3 + OH                                                           ', & ! index 118
     'HOCH2CO3H + OH --> HOCH2CO3                                                                         ', & ! index 119
     '     HOCH2CO3H --> HCHO + OH + HO2                                                                  ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(6) :: EQN_NAMES_4 = (/ &
     '          PHAN --> HOCH2CO3 + NO2                                                                   ', & ! index 121
     '     PHAN + OH --> CO + HCHO + NO2                                                                  ', & ! index 122
     '       RU12PAN --> RU12O2 + NO2                                                                     ', & ! index 123
     '  RU12PAN + OH --> UCARB10 + NO2                                                                    ', & ! index 124
     '  RU12OOH + OH --> RU12O2                                                                           ', & ! index 125
     '       RU12OOH --> CARB6 + HOCH2CHO + OH + HO2                                                      ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(126) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4 /)

  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: EQN_TAGS_0 = (/ &
     '               ','               ','               ', & ! index 1 - 3
     '               ','               ','               ', & ! index 4 - 6
     '               ','               ','               ', & ! index 7 - 9
     '               ','               ','               ', & ! index 10 - 12
     '               ','               ','               ', & ! index 13 - 15
     '               ','               ','               ', & ! index 16 - 18
     '               ','               ','               ', & ! index 19 - 21
     '               ','               ','               ', & ! index 22 - 24
     '               ','               ','               ', & ! index 25 - 27
     '               ','               ','               ', & ! index 28 - 30
     '               ','               ','               ', & ! index 31 - 33
     '               ','               ','               ', & ! index 34 - 36
     '               ','               ','               ', & ! index 37 - 39
     '               ','               ','               ', & ! index 40 - 42
     '               ','               ','               ', & ! index 43 - 45
     '0000           ','0003           ','0004           ', & ! index 46 - 48
     '0006           ','0034           ','0036           ', & ! index 49 - 51
     '0037           ','0053           ','0148           ', & ! index 52 - 54
     '0149           ','0150           ','0151           ', & ! index 55 - 57
     '0153           ','0154           ','0155           ', & ! index 58 - 60
     '0156           ','0157           ','0158           ', & ! index 61 - 63
     '0236           ','0237           ','0238           ', & ! index 64 - 66
     '0239           ','0240           ','0241           ', & ! index 67 - 69
     '0248           ','0249           ','0250           ', & ! index 70 - 72
     '0252           ','0426           ','0428           ', & ! index 73 - 75
     '0461           ','0462           ','0463           ', & ! index 76 - 78
     '0464           ','0465           ','0466           ', & ! index 79 - 81
     '0467           ','0468           ','0469           ', & ! index 82 - 84
     '0517           ','0518           ','0530           ', & ! index 85 - 87
     '0531           ','0532           ','0533           ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(36) :: EQN_TAGS_1 = (/ &
     '0534           ','0535           ','0536           ', & ! index 91 - 93
     '0538           ','0543           ','0544           ', & ! index 94 - 96
     '0545           ','0546           ','0547           ', & ! index 97 - 99
     '0548           ','0550           ','0551           ', & ! index 100 - 102
     '0721           ','0722           ','0723           ', & ! index 103 - 105
     '0724           ','0739           ','0740           ', & ! index 106 - 108
     '0744           ','0745           ','0746           ', & ! index 109 - 111
     '0747           ','0748           ','0749           ', & ! index 112 - 114
     '0758           ','0759           ','0760           ', & ! index 115 - 117
     '0761           ','0859           ','0860           ', & ! index 118 - 120
     '0861           ','0862           ','0863           ', & ! index 121 - 123
     '0864           ','0865           ','0866           ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(126) :: EQN_TAGS = (/&
    EQN_TAGS_0, EQN_TAGS_1 /)

  CHARACTER(LEN=15), DIMENSION(1) :: FAM_NAMES
! INLINED global variables

! End INLINED global variables


END MODULE model_Monitor
