! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Auxiliary Routines File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : model_Util.f90
! Time                 : Sun Nov 20 19:42:00 2016
! Working directory    : /work/home/dp626/DSMACC-testing
! Equation file        : model.kpp
! Output root filename : model
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE model_Util

  USE model_Parameters
  IMPLICIT NONE

CONTAINS



! User INLINED Utility Functions


SUBROUTINE InitVal (concs)

USE model_Global
use model_Monitor
INTEGER :: i,j,found
REAL(kind=dp) :: x
CHARACTER(LEN=10000) :: line
CHARACTER(LEN=15) :: test
REAL(kind=dp) :: concs(NSPEC)
REAL(kind=dp) :: oldvar(NSPEC)
INTEGER :: COUNT_NOX_CONSTRAINTS, i_CH4, i_H2 , i_EMISS
CHARACTER(len=6), dimension(8) :: NOXARRAY
NOXARRAY(:)= (/'NO2   ','NO    ','NO3   ','HONO  ','HNO2  ',&
    'HO2NO2','HNO4  ','PNA   '/)
    OLDVAR(1:NVAR)=C(1:NVAR)
    VAR(1:NVAR)=0.
    C(1:NVAR)=0.
    i_EMISS=0  
    DEPOS = 0.
    SAREA=0.
    ALBEDO=0.
    RP1=0.
    
    do I=1,NSPEC+1
    FOUND=0
    if (SPEC_NAME(I) .NE. '') then
    SPEC_NAME(I)=ADJUSTL(SPEC_NAME(I))

    do J=1,NVAR 

        if (TRIM(SPEC_NAME(I)) .EQ. TRIM(SPC_NAMES(J))) then 
        FOUND=1
        VAR(J)=CONCS(I)

        if (const_method(i) > 0) then 
             CONSTRAIN(J)=CONCS(I)
             print*, 'soft-constrained ', spec_name(i), 'at', constrain(j) 
        end if
             
        if (SPEC_NAME(I) .EQ. 'CH4') then 
        SPEC_CH4=.TRUE.
        i_CH4 = I

        else if (SPEC_NAME(I) .EQ. 'H2') then
        SPEC_H2=.TRUE.
        i_H2 = I 
        end if            

        endif

    enddo
    



    if (FOUND .ne. 1) then 

    SELECT CASE (TRIM(SPEC_NAME(I)))
   
    CASE('H2O') 
    H2O=CONCS(I)

    CASE('PRESS')  
    PRESS=CONCS(I)

    CASE('NOx') 
    CONSTRAIN_NOX=.TRUE.
    WRITE (OUTPUT_UNIT,*) 'Constraining total NOx concentation'

    CASE('LAT') 
    LAT=CONCS(I)

    CASE('LON')  
    LON=CONCS(I)

    CASE('TEMP') 
    TEMP=CONCS(I)

    CASE('JDAY')  
    JDAY=CONCS(I)

    CASE('TIME(GMTs)')  
    continue

    CASE('O3COL') 
    O3COL=CONCS(I)

    CASE('ALBEDO')  
    ALBEDO=CONCS(I)

    CASE('SAREA')  
    SAREA=CONCS(I)

    CASE('RP1')  
    RP1=CONCS(I)

    CASE('JNO2') 
        if (CONST_METHOD(I) .GE. 1) JNO2=CONCS(I)

        JREPEAT=0

        if (CONST_METHOD(I) .EQ. 2) JREPEAT=1


    CASE('JO1D') 

        if (CONST_METHOD(I) .GE. 1) JO1D=CONCS(I)

        JREPEAT=0

        if (CONST_METHOD(I) .EQ. 2) JREPEAT=1


    CASE('DEPOS') 

        if (CONCS(I) > 0) then  
            DEPOS = 1.
            print *, 'DEPOSITON ENABLED'
        end if 


    CASE DEFAULT
    !! for any species in the fixed array 
    if (SPEC_NAME(I)(1:1) .EQ. 'F')  then   
        SPEC_NAME(i)  = SPEC_NAME(i)(2:)

        do J=NVAR+1,NVAR+NFIX    
         
            if (TRIM(SPEC_NAME(I)) .EQ. TRIM(SPC_NAMES(J))) then 
                FOUND=1
                FIX(J-NVAR)=CONCS(I)
                print*, 'hard-constrained ', spec_name(i), ' at ', concs(I)
                    
                if (SPEC_NAME(I) .EQ. 'EMISS') then
                    i_EMISS = (J-NVAR)        
                else if (SPEC_NAME(I) .EQ. 'CH4') then 
                    SPEC_CH4=.TRUE.
                    i_CH4 = I
                else if (SPEC_NAME(I) .EQ. 'H2') then
                    SPEC_H2=.TRUE.
                    i_H2 = I               
                end if            
            else 
                    WRITE(OUTPUT_UNIT,*) SPEC_NAME(I),' NOT FOUND - stopping'
                    WRITE(6,*) SPEC_NAME(I),' NOT FOUND - stopping'
                    stop 
            endif
            
        enddo
    
    else if (SPEC_NAME(I)(1:1) .NE. 'X') then 
        WRITE(OUTPUT_UNIT,*) SPEC_NAME(I),' NOT FOUND - stopping'
        WRITE(6,*) SPEC_NAME(I),' NOT FOUND - stopping '
        stop   
        end if 
        WRITE (OUTPUT_UNIT,*) 'Starts with X => ignored'   
 
    
    END SELECT
    endif
    endif


    enddo

    !convert to mol cm-3s-1
    CFACTOR=PRESS*1e2*1e-6/(8.314*TEMP)*6.022E23
    H2O=H2O*CFACTOR 
    VAR(:)=VAR(:)*CFACTOR
    CONSTRAIN(:)=CONSTRAIN(:)*CFACTOR
    FIX(:)=FIX(:)*CFACTOR
    if (i_EMISS>0) FIX(i_EMISS)= FIX(i_EMISS)/CFACTOR 
    !correct emissions ^^

    
    if (CONSTRAIN_NOX) then 
        COUNT_NOX_CONSTRAINTS=0


        do I=1,NVAR 
        do j= 1,8 

        if (TRIM(SPC_NAMES(I)) .EQ. TRIM(NOXARRAY(j))) then 
        NOX(I)=1
        CONSTRAIN(I)=-1.*CONSTRAIN(I)
        if (CONSTRAIN(I) .NE. 0 .and.&  
            TRIM(SPC_NAMES(I)).ne. 'PNA')& 
            COUNT_NOX_CONSTRAINTS=COUNT_NOX_CONSTRAINTS+1
            WRITE (OUTPUT_UNIT,*) SPC_NAMES(I),' IN NOX FAMILY'
            exit
            end if
            end do 

            if (TRIM(SPC_NAMES(I)) .EQ. 'N2O5') then
            NOX(I)=2
            CONSTRAIN(I)=-1.*CONSTRAIN(I)
            if (CONSTRAIN(I) .NE. 0)  COUNT_NOX_CONSTRAINTS=&
            COUNT_NOX_CONSTRAINTS+1
            endif

            end do

            if (COUNT_NOX_CONSTRAINTS .GT. 1) then 
            WRITE (OUTPUT_UNIT,*) 'You can not contrain multiple NOX species'
            STOP
            endif

    end if


        ! FIND CH4 and H2 species
        if (SPEC_CH4 .EQv. .FALSE. .and. i_CH4 .ne. 0) then
        WRITE (OUTPUT_UNIT,*) 'No CH4 specified assuming 1770 ppbv'
        VAR(i_CH4)=1770e-9*CFACTOR
        CONSTRAIN(i_CH4)=VAR(i_CH4)
        end if

        if (SPEC_H2 .EQv. .FALSE. .and. i_H2 .ne. 0) then 
        WRITE (OUTPUT_UNIT,*) 'No H2 specified assuming 550 ppbv'
        VAR(i_H2)= 550e-9*CFACTOR
        CONSTRAIN(i_H2)=VAR(i_H2)
        end if




        END SUBROUTINE Initval
        ! End of InitVal function
        ! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


        ! ****************************************************************
        ! ****************************************************************
        !                            
        ! SaveData - Write LOOKAT species in the data file 
        !   Parameters :  index_loc = daycounter                                
        !
        ! ****************************************************************

        subroutine SaveOut(index_loc)
        USE model_Global
        USE model_Monitor
        USE model_Integrator
        integer :: index_loc
        
        !print *, 'adjust to reflect multiple times'
        !spec
        output_s(index_loc,1)=Jday*86400  + DAYCOUNTER*dt 
        output_s(index_loc,2)=Lat
        output_s(index_loc,3)=Lon
        output_s(index_loc,4)=Press
        output_s(index_loc,5)=Temp
        output_s(index_loc,6)=H2O
        output_s(index_loc,7)=Cfactor
        output_s(index_loc,8)=JfactNO2
        output_s(index_loc,9)=JfactO1D
        output_s(index_loc,10)=RO2
        output_s(index_loc,11:) = C 
        !rate
        output_r(index_loc,1)=Jday*86400  + DAYCOUNTER*dt 
        output_r(index_loc,2)=Lat
        output_r(index_loc,3)=Lon
        output_r(index_loc,4)=Press
        output_r(index_loc,5)=Temp
        output_r(index_loc,6)=H2O
        output_r(index_loc,7:) = Rconst
 
        end subroutine SaveOut

      
        ! ****************************************************************


        SUBROUTINE ICNVRT(WAY,NUM,STRING,LENGTH,IERR)
        !
        !       FUNCTION:
        !F
        !F        This subroutine does an integer-to-character conversion
        !F        or a characater-to-integer conversion depending on the
        !F        integer WAY:
        !F                If WAY = 0 then an integer-to-character conversion
        !F                is done. If WAY .NE. 0 then a character-to-integer
        !F                conversion is done.
        !F
        !       USAGE:
        !U
        !U        !ALL I!NVRT(WAY,NUM,STRING)[
        !U             where WAY, NUM, STRING, and LENGTH are defined below.
        !U
        !U        Example: !ALL I!NVRT(0,1000,STRING,LENGTH)
        !U                 on return STRING = '1000' and
        !U                 LENGTH = 4.
        !U         
        !       INPUTS:
        !I
        !I        WAY - INTEGER; Determines which way the conversion goes:
        !I              if WAY = 0 then an integer-to-character conversion
        !I                         is performed;
        !I              if WAY.NE.0 then a character-to-integer conversion
        !I                         is performed.
        !I
        !I         NUM - INTEGER; an input only if WAY = 0. NUM is the integer
        !I               number to be converted to a character expression.
        !I
        !I         STRING - !HARACTER; an input only if WAY .NE. 0. STRING
        !I                is the character expression to be converted to an
        !CI                integer value. It contain no decimal points or 
        !I                non-numeric characters other than possibly a
        !I                sign. If STRING contains  a '+' sign, it will be
        !I                stripped of it on return.
        !I
        !       OUTPUTS:
        !O
        !O         NUM - INTEGER; contains the INTEGER representation of 
        !O                STRING.
        !O
        !O         STRING - !HARA!TER; contains the CHARACTER representation of
        !O                  NUM.
        !CO
        !CO         LENGTH - INTEGER; The length of STRING to the first blank.
        !CO                  The significant part of STRING can be accessed with
        !CO                  the declaration STRING(1:LENGTH).
        !CO
        !CO         IERR - INTEGER variable giving return condition:
        !CO                IERR = 0 for normal return;
        !CO                IERR = 1 if NUM cannot be converted to STRING because
        !CO                       STRING is too short or STRING cannot be
        !CO                       converted to NUM because STRING is too long.
        !CO                IERR = 2 if STRING contained a non-numeric character
        !CO                       other than a leading sign or something went
        !CO                       wrong with an integer-to-character conversion.
        !CO
        !C       ALGORITHM:
        !CA
        !CA         Nothing noteworthy, except that this subroutine will work
        !CA          for strange character sets where the character '1' doesn't
        !CA          follow '0', etc.
        !CA
        !C       MACHINE DEPENDENCIES:
        !CM
        !CM          The parameter MAXINT (below) should be set to the
        !CM          number of digits that an INTEGER data type can have
        !CM          not including leading signs. For VAX FORTRAN V4.4-177
        !CM          MAXINT = 10.
        !CM
        !CM          NOTE: Under VAX FORTRAN V4.4-177, the
        !CM          error condition IERR = 1 will never occur for an
        !CM          integer-to-character conversion if STRING
        !CM          is allocated at least 11 bytes (CHARACTER*11).
        !CM
        !C       HISTORY:
        !CH
        !CH      written by:             bobby bodenheimer
        !CH      date:                   september 1986
        !CH      current version:        1.0
        !CH      modifications:          none
        !CH
        !C       ROUTINES CALLED:
        !CC
        !CC          NONE.
        !CC
        !C----------------------------------------------------------------------
        !C       written for:    The CASCADE Project
        !C                       Oak Ridge National Laboratory
        !C                       U.S. Department of Energy
        !C                       contract number DE-AC05-840R21400
        !C                       subcontract number 37B-7685 S13
        !C                       organization:  The University of Tennessee
        !C----------------------------------------------------------------------
        !C       THIS SOFTWARE IS IN THE PUBLIC DOMAIN
        !C       NO RESTRICTIONS ON ITS USE ARE IMPLIED
        !C----------------------------------------------------------------------
        !C
        !C Global Variables.
        !C
        INTEGER       WAY
        INTEGER       LENGTH
        INTEGER       NUM
        INTEGER       IERR
        CHARACTER*(*) STRING
        !C    
        !C Local Variables
        !C
        INTEGER       I
        INTEGER       MAXINT
        INTEGER       MNUM
        INTEGER       M
        LOGICAL       NEG
        character(1) dummy
        integer    dummyvar
        !C
        PARAMETER(MAXINT=10)
        !C
        NEG = .FALSE.
        IERR = 0
        !C
        !C  Integer-to-character conversion.
        !C
        IF (WAY.EQ.0) THEN
        STRING = ' '
        IF (NUM.LT.0) THEN
        NEG = .TRUE.
        MNUM = -NUM
        LENGTH = INT(LOG10(REAL(MNUM))) + 1
        ELSE IF (NUM.EQ.0) THEN
        MNUM = NUM
        LENGTH = 1
        ELSE
        MNUM = NUM
        LENGTH = INT(LOG10(REAL(MNUM))) + 1
        END IF
        IF (LENGTH.GT.LEN(STRING)) THEN
        IERR = 1
        RETURN
        END IF


        DO 10, I=LENGTH,1,-1
        M=INT(REAL(MNUM)/10**(I-1))

        !jkhjkhjkhjkhljhlkjhj 
        if (m.lt.10) then 
        Write( dummy, '(i1)' ) M
        STRING(LENGTH-I+1:LENGTH-I+1) = dummy
        ELSE
        IERR = 2
        RETURN
        END IF


        MNUM = MNUM - M*10**(I-1)
        10       CONTINUE
        IF (NEG) THEN
        STRING = '-'//STRING
        LENGTH = LENGTH + 1
        END IF
        !C
        !C  Character-to-integer conversion.
        !!C
        ELSE
        IF (STRING(1:1).EQ.'-') THEN
        NEG = .TRUE.
        STRING = STRING(2:LEN(STRING))
        END IF
        IF (STRING(1:1).EQ.'+') STRING = STRING(2:LEN(STRING))
        NUM = 0
        LENGTH = INDEX(STRING,' ') - 1
        IF (LENGTH.GT.MAXINT) THEN
        IERR = 1
        RETURN
        END IF


        DO 20, I=LENGTH,1,-1           
        read( STRING(LENGTH-I+1:LENGTH-I+1), '(i10)' ) dummyvar
        if (dummyvar.lt.10) then 
        M= (dummyvar) 
        ELSE
        IERR = 2
        RETURN
        END IF

        NUM = NUM + INT(10**(I-1))*M
        20       CONTINUE

        IF (NEG) THEN
        NUM = -NUM
        STRING = '-'//STRING
        LENGTH = LENGTH + 1
        END IF
        END IF
        !C
        !C  Last lines of ICNVRT
        !C
        RETURN
        END SUBROUTINE


        
! End INLINED Utility Functions

! Utility Functions from KPP_HOME/util/util
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! UTIL - Utility functions
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! ****************************************************************
!                            
! InitSaveData - Opens the data file for writing
!   Parameters :                                                  
!
! ****************************************************************

      SUBROUTINE InitSaveData ()

      USE model_Parameters

      open(10, file='model.dat')

      END SUBROUTINE InitSaveData

! End of InitSaveData function
! ****************************************************************

! ****************************************************************
!                            
! SaveData - Write LOOKAT species in the data file 
!   Parameters :                                                  
!
! ****************************************************************

      SUBROUTINE SaveData ()

      USE model_Global
      USE model_Monitor

      INTEGER i

      WRITE(10,999) (TIME-TSTART)/3600.D0,  &
                   (C(LOOKAT(i))/CFACTOR, i=1,NLOOKAT)
999   FORMAT(E24.16,100(1X,E24.16))

      END SUBROUTINE SaveData

! End of SaveData function
! ****************************************************************

! ****************************************************************
!                            
! CloseSaveData - Close the data file 
!   Parameters :                                                  
!
! ****************************************************************

      SUBROUTINE CloseSaveData ()

      USE model_Parameters

      CLOSE(10)

      END SUBROUTINE CloseSaveData

! End of CloseSaveData function
! ****************************************************************

! ****************************************************************
!                            
! GenerateMatlab - Generates MATLAB file to load the data file 
!   Parameters : 
!                It will have a character string to prefix each 
!                species name with.                                                 
!
! ****************************************************************

      SUBROUTINE GenerateMatlab ( PREFIX )

      USE model_Parameters
      USE model_Global
      USE model_Monitor

      
      CHARACTER(LEN=8) PREFIX 
      INTEGER i

      open(20, file='model.m')
      write(20,*) 'load model.dat;'
      write(20,990) PREFIX
990   FORMAT(A1,'c = model;')
      write(20,*) 'clear model;'
      write(20,991) PREFIX, PREFIX
991   FORMAT(A1,'t=',A1,'c(:,1);')
      write(20,992) PREFIX
992   FORMAT(A1,'c(:,1)=[];')

      do i=1,NLOOKAT
        write(20,993) PREFIX, SPC_NAMES(LOOKAT(i)), PREFIX, i
993     FORMAT(A1,A6,' = ',A1,'c(:,',I2,');')
      end do
      
      CLOSE(20)

      END SUBROUTINE GenerateMatlab

! End of GenerateMatlab function
! ****************************************************************


! ****************************************************************
!                            
! tag2num - convert equation tags to kpp reaction number
!   Arguments :
!      id        - string with the equation tag
!
! ****************************************************************

ELEMENTAL INTEGER FUNCTION tag2num ( id )

  USE model_Monitor, ONLY: EQN_TAGS

  CHARACTER(LEN=*), INTENT(IN) :: id
  INTEGER i

  tag2num = 0 ! mz_rs_20050115
  DO i = 1, SIZE(EQN_TAGS)
    IF (TRIM(EQN_TAGS(i)) == TRIM(id)) THEN
      tag2num = i ! mz_rs_20050115
      EXIT
    ENDIF
  END DO

END FUNCTION tag2num

! End of tag2num function
! ****************************************************************

! End Utility Functions from KPP_HOME/util/util
! End of UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Shuffle_user2kpp - function to copy concentrations from USER to KPP
!   Arguments :
!      V_USER    - Concentration of variable species in USER's order
!      V         - Concentrations of variable species (local)
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_user2kpp ( V_USER, V )

! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)
! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)

  V(252) = V_USER(1)
  V(437) = V_USER(2)
  V(481) = V_USER(3)
  V(482) = V_USER(4)
  V(38) = V_USER(5)
  V(385) = V_USER(6)
  V(818) = V_USER(7)
  V(687) = V_USER(8)
  V(36) = V_USER(9)
  V(662) = V_USER(10)
  V(402) = V_USER(11)
  V(360) = V_USER(12)
  V(198) = V_USER(13)
  V(256) = V_USER(14)
  V(185) = V_USER(15)
  V(617) = V_USER(16)
  V(96) = V_USER(17)
  V(886) = V_USER(18)
  V(162) = V_USER(19)
  V(60) = V_USER(20)
  V(625) = V_USER(21)
  V(787) = V_USER(22)
  V(394) = V_USER(23)
  V(292) = V_USER(24)
  V(295) = V_USER(25)
  V(412) = V_USER(26)
  V(331) = V_USER(27)
  V(553) = V_USER(28)
  V(13) = V_USER(29)
  V(70) = V_USER(30)
  V(748) = V_USER(31)
  V(615) = V_USER(32)
  V(221) = V_USER(33)
  V(517) = V_USER(34)
  V(540) = V_USER(35)
  V(689) = V_USER(36)
  V(802) = V_USER(37)
  V(384) = V_USER(38)
  V(319) = V_USER(39)
  V(49) = V_USER(40)
  V(513) = V_USER(41)
  V(610) = V_USER(42)
  V(730) = V_USER(43)
  V(391) = V_USER(44)
  V(242) = V_USER(45)
  V(770) = V_USER(46)
  V(323) = V_USER(47)
  V(243) = V_USER(48)
  V(502) = V_USER(49)
  V(654) = V_USER(50)
  V(460) = V_USER(51)
  V(14) = V_USER(52)
  V(81) = V_USER(53)
  V(769) = V_USER(54)
  V(700) = V_USER(55)
  V(111) = V_USER(56)
  V(448) = V_USER(57)
  V(279) = V_USER(58)
  V(165) = V_USER(59)
  V(166) = V_USER(60)
  V(167) = V_USER(61)
  V(302) = V_USER(62)
  V(241) = V_USER(63)
  V(123) = V_USER(64)
  V(124) = V_USER(65)
  V(646) = V_USER(66)
  V(336) = V_USER(67)
  V(669) = V_USER(68)
  V(679) = V_USER(69)
  V(435) = V_USER(70)
  V(893) = V_USER(71)
  V(205) = V_USER(72)
  V(361) = V_USER(73)
  V(734) = V_USER(74)
  V(665) = V_USER(75)
  V(363) = V_USER(76)
  V(250) = V_USER(77)
  V(588) = V_USER(78)
  V(453) = V_USER(79)
  V(567) = V_USER(80)
  V(393) = V_USER(81)
  V(374) = V_USER(82)
  V(371) = V_USER(83)
  V(745) = V_USER(84)
  V(522) = V_USER(85)
  V(575) = V_USER(86)
  V(438) = V_USER(87)
  V(43) = V_USER(88)
  V(728) = V_USER(89)
  V(442) = V_USER(90)
  V(568) = V_USER(91)
  V(817) = V_USER(92)
  V(69) = V_USER(93)
  V(232) = V_USER(94)
  V(658) = V_USER(95)
  V(297) = V_USER(96)
  V(314) = V_USER(97)
  V(673) = V_USER(98)
  V(340) = V_USER(99)
  V(578) = V_USER(100)
  V(791) = V_USER(101)
  V(432) = V_USER(102)
  V(601) = V_USER(103)
  V(260) = V_USER(104)
  V(265) = V_USER(105)
  V(152) = V_USER(106)
  V(153) = V_USER(107)
  V(643) = V_USER(108)
  V(550) = V_USER(109)
  V(881) = V_USER(110)
  V(87) = V_USER(111)
  V(683) = V_USER(112)
  V(44) = V_USER(113)
  V(386) = V_USER(114)
  V(852) = V_USER(115)
  V(174) = V_USER(116)
  V(303) = V_USER(117)
  V(532) = V_USER(118)
  V(88) = V_USER(119)
  V(45) = V_USER(120)
  V(184) = V_USER(121)
  V(621) = V_USER(122)
  V(15) = V_USER(123)
  V(417) = V_USER(124)
  V(191) = V_USER(125)
  V(680) = V_USER(126)
  V(722) = V_USER(127)
  V(89) = V_USER(128)
  V(90) = V_USER(129)
  V(443) = V_USER(130)
  V(210) = V_USER(131)
  V(91) = V_USER(132)
  V(609) = V_USER(133)
  V(396) = V_USER(134)
  V(92) = V_USER(135)
  V(93) = V_USER(136)
  V(291) = V_USER(137)
  V(755) = V_USER(138)
  V(799) = V_USER(139)
  V(744) = V_USER(140)
  V(524) = V_USER(141)
  V(94) = V_USER(142)
  V(253) = V_USER(143)
  V(95) = V_USER(144)
  V(134) = V_USER(145)
  V(816) = V_USER(146)
  V(387) = V_USER(147)
  V(605) = V_USER(148)
  V(514) = V_USER(149)
  V(264) = V_USER(150)
  V(414) = V_USER(151)
  V(16) = V_USER(152)
  V(859) = V_USER(153)
  V(574) = V_USER(154)
  V(423) = V_USER(155)
  V(236) = V_USER(156)
  V(486) = V_USER(157)
  V(275) = V_USER(158)
  V(631) = V_USER(159)
  V(760) = V_USER(160)
  V(655) = V_USER(161)
  V(548) = V_USER(162)
  V(641) = V_USER(163)
  V(135) = V_USER(164)
  V(690) = V_USER(165)
  V(239) = V_USER(166)
  V(289) = V_USER(167)
  V(554) = V_USER(168)
  V(582) = V_USER(169)
  V(880) = V_USER(170)
  V(803) = V_USER(171)
  V(17) = V_USER(172)
  V(298) = V_USER(173)
  V(583) = V_USER(174)
  V(685) = V_USER(175)
  V(757) = V_USER(176)
  V(623) = V_USER(177)
  V(97) = V_USER(178)
  V(315) = V_USER(179)
  V(538) = V_USER(180)
  V(46) = V_USER(181)
  V(39) = V_USER(182)
  V(415) = V_USER(183)
  V(98) = V_USER(184)
  V(742) = V_USER(185)
  V(579) = V_USER(186)
  V(670) = V_USER(187)
  V(418) = V_USER(188)
  V(47) = V_USER(189)
  V(48) = V_USER(190)
  V(696) = V_USER(191)
  V(684) = V_USER(192)
  V(828) = V_USER(193)
  V(500) = V_USER(194)
  V(40) = V_USER(195)
  V(424) = V_USER(196)
  V(99) = V_USER(197)
  V(530) = V_USER(198)
  V(50) = V_USER(199)
  V(342) = V_USER(200)
  V(434) = V_USER(201)
  V(882) = V_USER(202)
  V(835) = V_USER(203)
  V(706) = V_USER(204)
  V(811) = V_USER(205)
  V(356) = V_USER(206)
  V(762) = V_USER(207)
  V(851) = V_USER(208)
  V(100) = V_USER(209)
  V(725) = V_USER(210)
  V(536) = V_USER(211)
  V(674) = V_USER(212)
  V(616) = V_USER(213)
  V(136) = V_USER(214)
  V(375) = V_USER(215)
  V(51) = V_USER(216)
  V(738) = V_USER(217)
  V(376) = V_USER(218)
  V(764) = V_USER(219)
  V(463) = V_USER(220)
  V(489) = V_USER(221)
  V(464) = V_USER(222)
  V(648) = V_USER(223)
  V(858) = V_USER(224)
  V(714) = V_USER(225)
  V(754) = V_USER(226)
  V(471) = V_USER(227)
  V(251) = V_USER(228)
  V(477) = V_USER(229)
  V(383) = V_USER(230)
  V(137) = V_USER(231)
  V(724) = V_USER(232)
  V(461) = V_USER(233)
  V(138) = V_USER(234)
  V(589) = V_USER(235)
  V(436) = V_USER(236)
  V(445) = V_USER(237)
  V(535) = V_USER(238)
  V(804) = V_USER(239)
  V(231) = V_USER(240)
  V(307) = V_USER(241)
  V(526) = V_USER(242)
  V(139) = V_USER(243)
  V(729) = V_USER(244)
  V(487) = V_USER(245)
  V(140) = V_USER(246)
  V(692) = V_USER(247)
  V(779) = V_USER(248)
  V(810) = V_USER(249)
  V(368) = V_USER(250)
  V(472) = V_USER(251)
  V(141) = V_USER(252)
  V(533) = V_USER(253)
  V(499) = V_USER(254)
  V(142) = V_USER(255)
  V(143) = V_USER(256)
  V(869) = V_USER(257)
  V(101) = V_USER(258)
  V(144) = V_USER(259)
  V(145) = V_USER(260)
  V(676) = V_USER(261)
  V(883) = V_USER(262)
  V(717) = V_USER(263)
  V(407) = V_USER(264)
  V(661) = V_USER(265)
  V(850) = V_USER(266)
  V(686) = V_USER(267)
  V(254) = V_USER(268)
  V(552) = V_USER(269)
  V(783) = V_USER(270)
  V(720) = V_USER(271)
  V(255) = V_USER(272)
  V(102) = V_USER(273)
  V(52) = V_USER(274)
  V(257) = V_USER(275)
  V(146) = V_USER(276)
  V(233) = V_USER(277)
  V(870) = V_USER(278)
  V(637) = V_USER(279)
  V(467) = V_USER(280)
  V(258) = V_USER(281)
  V(259) = V_USER(282)
  V(701) = V_USER(283)
  V(53) = V_USER(284)
  V(103) = V_USER(285)
  V(519) = V_USER(286)
  V(104) = V_USER(287)
  V(718) = V_USER(288)
  V(54) = V_USER(289)
  V(868) = V_USER(290)
  V(838) = V_USER(291)
  V(55) = V_USER(292)
  V(595) = V_USER(293)
  V(403) = V_USER(294)
  V(872) = V_USER(295)
  V(261) = V_USER(296)
  V(147) = V_USER(297)
  V(708) = V_USER(298)
  V(148) = V_USER(299)
  V(149) = V_USER(300)
  V(262) = V_USER(301)
  V(234) = V_USER(302)
  V(406) = V_USER(303)
  V(263) = V_USER(304)
  V(580) = V_USER(305)
  V(150) = V_USER(306)
  V(408) = V_USER(307)
  V(105) = V_USER(308)
  V(542) = V_USER(309)
  V(626) = V_USER(310)
  V(884) = V_USER(311)
  V(812) = V_USER(312)
  V(491) = V_USER(313)
  V(576) = V_USER(314)
  V(547) = V_USER(315)
  V(151) = V_USER(316)
  V(106) = V_USER(317)
  V(107) = V_USER(318)
  V(154) = V_USER(319)
  V(483) = V_USER(320)
  V(585) = V_USER(321)
  V(266) = V_USER(322)
  V(716) = V_USER(323)
  V(108) = V_USER(324)
  V(109) = V_USER(325)
  V(235) = V_USER(326)
  V(267) = V_USER(327)
  V(814) = V_USER(328)
  V(620) = V_USER(329)
  V(268) = V_USER(330)
  V(269) = V_USER(331)
  V(110) = V_USER(332)
  V(763) = V_USER(333)
  V(651) = V_USER(334)
  V(698) = V_USER(335)
  V(805) = V_USER(336)
  V(155) = V_USER(337)
  V(849) = V_USER(338)
  V(270) = V_USER(339)
  V(427) = V_USER(340)
  V(272) = V_USER(341)
  V(429) = V_USER(342)
  V(273) = V_USER(343)
  V(156) = V_USER(344)
  V(56) = V_USER(345)
  V(157) = V_USER(346)
  V(586) = V_USER(347)
  V(274) = V_USER(348)
  V(847) = V_USER(349)
  V(622) = V_USER(350)
  V(158) = V_USER(351)
  V(824) = V_USER(352)
  V(832) = V_USER(353)
  V(598) = V_USER(354)
  V(237) = V_USER(355)
  V(507) = V_USER(356)
  V(691) = V_USER(357)
  V(599) = V_USER(358)
  V(753) = V_USER(359)
  V(57) = V_USER(360)
  V(276) = V_USER(361)
  V(564) = V_USER(362)
  V(577) = V_USER(363)
  V(238) = V_USER(364)
  V(732) = V_USER(365)
  V(735) = V_USER(366)
  V(18) = V_USER(367)
  V(644) = V_USER(368)
  V(789) = V_USER(369)
  V(278) = V_USER(370)
  V(58) = V_USER(371)
  V(159) = V_USER(372)
  V(831) = V_USER(373)
  V(160) = V_USER(374)
  V(834) = V_USER(375)
  V(112) = V_USER(376)
  V(280) = V_USER(377)
  V(161) = V_USER(378)
  V(878) = V_USER(379)
  V(470) = V_USER(380)
  V(19) = V_USER(381)
  V(163) = V_USER(382)
  V(164) = V_USER(383)
  V(873) = V_USER(384)
  V(59) = V_USER(385)
  V(281) = V_USER(386)
  V(20) = V_USER(387)
  V(766) = V_USER(388)
  V(425) = V_USER(389)
  V(874) = V_USER(390)
  V(282) = V_USER(391)
  V(283) = V_USER(392)
  V(558) = V_USER(393)
  V(113) = V_USER(394)
  V(555) = V_USER(395)
  V(21) = V_USER(396)
  V(496) = V_USER(397)
  V(392) = V_USER(398)
  V(593) = V_USER(399)
  V(531) = V_USER(400)
  V(22) = V_USER(401)
  V(284) = V_USER(402)
  V(862) = V_USER(403)
  V(114) = V_USER(404)
  V(285) = V_USER(405)
  V(23) = V_USER(406)
  V(286) = V_USER(407)
  V(395) = V_USER(408)
  V(798) = V_USER(409)
  V(287) = V_USER(410)
  V(776) = V_USER(411)
  V(678) = V_USER(412)
  V(788) = V_USER(413)
  V(115) = V_USER(414)
  V(721) = V_USER(415)
  V(774) = V_USER(416)
  V(397) = V_USER(417)
  V(541) = V_USER(418)
  V(527) = V_USER(419)
  V(860) = V_USER(420)
  V(288) = V_USER(421)
  V(398) = V_USER(422)
  V(889) = V_USER(423)
  V(61) = V_USER(424)
  V(759) = V_USER(425)
  V(399) = V_USER(426)
  V(290) = V_USER(427)
  V(168) = V_USER(428)
  V(169) = V_USER(429)
  V(240) = V_USER(430)
  V(24) = V_USER(431)
  V(170) = V_USER(432)
  V(705) = V_USER(433)
  V(778) = V_USER(434)
  V(400) = V_USER(435)
  V(401) = V_USER(436)
  V(293) = V_USER(437)
  V(8) = V_USER(438)
  V(822) = V_USER(439)
  V(854) = V_USER(440)
  V(11) = V_USER(441)
  V(559) = V_USER(442)
  V(739) = V_USER(443)
  V(561) = V_USER(444)
  V(879) = V_USER(445)
  V(534) = V_USER(446)
  V(294) = V_USER(447)
  V(25) = V_USER(448)
  V(545) = V_USER(449)
  V(652) = V_USER(450)
  V(537) = V_USER(451)
  V(602) = V_USER(452)
  V(296) = V_USER(453)
  V(509) = V_USER(454)
  V(171) = V_USER(455)
  V(604) = V_USER(456)
  V(172) = V_USER(457)
  V(173) = V_USER(458)
  V(632) = V_USER(459)
  V(855) = V_USER(460)
  V(570) = V_USER(461)
  V(299) = V_USER(462)
  V(404) = V_USER(463)
  V(116) = V_USER(464)
  V(300) = V_USER(465)
  V(301) = V_USER(466)
  V(573) = V_USER(467)
  V(405) = V_USER(468)
  V(607) = V_USER(469)
  V(539) = V_USER(470)
  V(795) = V_USER(471)
  V(62) = V_USER(472)
  V(608) = V_USER(473)
  V(813) = V_USER(474)
  V(797) = V_USER(475)
  V(117) = V_USER(476)
  V(304) = V_USER(477)
  V(305) = V_USER(478)
  V(306) = V_USER(479)
  V(781) = V_USER(480)
  V(642) = V_USER(481)
  V(741) = V_USER(482)
  V(727) = V_USER(483)
  V(175) = V_USER(484)
  V(63) = V_USER(485)
  V(409) = V_USER(486)
  V(176) = V_USER(487)
  V(844) = V_USER(488)
  V(864) = V_USER(489)
  V(410) = V_USER(490)
  V(411) = V_USER(491)
  V(833) = V_USER(492)
  V(490) = V_USER(493)
  V(856) = V_USER(494)
  V(308) = V_USER(495)
  V(775) = V_USER(496)
  V(309) = V_USER(497)
  V(645) = V_USER(498)
  V(310) = V_USER(499)
  V(843) = V_USER(500)
  V(311) = V_USER(501)
  V(313) = V_USER(502)
  V(118) = V_USER(503)
  V(876) = V_USER(504)
  V(177) = V_USER(505)
  V(492) = V_USER(506)
  V(773) = V_USER(507)
  V(493) = V_USER(508)
  V(26) = V_USER(509)
  V(871) = V_USER(510)
  V(178) = V_USER(511)
  V(413) = V_USER(512)
  V(786) = V_USER(513)
  V(800) = V_USER(514)
  V(179) = V_USER(515)
  V(180) = V_USER(516)
  V(316) = V_USER(517)
  V(826) = V_USER(518)
  V(317) = V_USER(519)
  V(318) = V_USER(520)
  V(181) = V_USER(521)
  V(182) = V_USER(522)
  V(183) = V_USER(523)
  V(772) = V_USER(524)
  V(556) = V_USER(525)
  V(119) = V_USER(526)
  V(808) = V_USER(527)
  V(752) = V_USER(528)
  V(653) = V_USER(529)
  V(320) = V_USER(530)
  V(321) = V_USER(531)
  V(857) = V_USER(532)
  V(525) = V_USER(533)
  V(120) = V_USER(534)
  V(667) = V_USER(535)
  V(121) = V_USER(536)
  V(520) = V_USER(537)
  V(322) = V_USER(538)
  V(712) = V_USER(539)
  V(715) = V_USER(540)
  V(122) = V_USER(541)
  V(64) = V_USER(542)
  V(312) = V_USER(543)
  V(668) = V_USER(544)
  V(494) = V_USER(545)
  V(416) = V_USER(546)
  V(186) = V_USER(547)
  V(768) = V_USER(548)
  V(495) = V_USER(549)
  V(187) = V_USER(550)
  V(65) = V_USER(551)
  V(630) = V_USER(552)
  V(647) = V_USER(553)
  V(677) = V_USER(554)
  V(751) = V_USER(555)
  V(188) = V_USER(556)
  V(694) = V_USER(557)
  V(597) = V_USER(558)
  V(189) = V_USER(559)
  V(190) = V_USER(560)
  V(388) = V_USER(561)
  V(497) = V_USER(562)
  V(743) = V_USER(563)
  V(723) = V_USER(564)
  V(419) = V_USER(565)
  V(498) = V_USER(566)
  V(125) = V_USER(567)
  V(681) = V_USER(568)
  V(633) = V_USER(569)
  V(731) = V_USER(570)
  V(634) = V_USER(571)
  V(192) = V_USER(572)
  V(484) = V_USER(573)
  V(801) = V_USER(574)
  V(782) = V_USER(575)
  V(420) = V_USER(576)
  V(324) = V_USER(577)
  V(325) = V_USER(578)
  V(326) = V_USER(579)
  V(433) = V_USER(580)
  V(421) = V_USER(581)
  V(66) = V_USER(582)
  V(636) = V_USER(583)
  V(842) = V_USER(584)
  V(853) = V_USER(585)
  V(193) = V_USER(586)
  V(796) = V_USER(587)
  V(629) = V_USER(588)
  V(327) = V_USER(589)
  V(887) = V_USER(590)
  V(328) = V_USER(591)
  V(244) = V_USER(592)
  V(675) = V_USER(593)
  V(543) = V_USER(594)
  V(592) = V_USER(595)
  V(329) = V_USER(596)
  V(719) = V_USER(597)
  V(422) = V_USER(598)
  V(551) = V_USER(599)
  V(330) = V_USER(600)
  V(528) = V_USER(601)
  V(194) = V_USER(602)
  V(27) = V_USER(603)
  V(332) = V_USER(604)
  V(333) = V_USER(605)
  V(28) = V_USER(606)
  V(335) = V_USER(607)
  V(67) = V_USER(608)
  V(337) = V_USER(609)
  V(501) = V_USER(610)
  V(780) = V_USER(611)
  V(338) = V_USER(612)
  V(68) = V_USER(613)
  V(195) = V_USER(614)
  V(126) = V_USER(615)
  V(529) = V_USER(616)
  V(196) = V_USER(617)
  V(389) = V_USER(618)
  V(426) = V_USER(619)
  V(711) = V_USER(620)
  V(339) = V_USER(621)
  V(197) = V_USER(622)
  V(682) = V_USER(623)
  V(885) = V_USER(624)
  V(127) = V_USER(625)
  V(704) = V_USER(626)
  V(341) = V_USER(627)
  V(29) = V_USER(628)
  V(199) = V_USER(629)
  V(428) = V_USER(630)
  V(618) = V_USER(631)
  V(128) = V_USER(632)
  V(200) = V_USER(633)
  V(785) = V_USER(634)
  V(485) = V_USER(635)
  V(806) = V_USER(636)
  V(594) = V_USER(637)
  V(430) = V_USER(638)
  V(431) = V_USER(639)
  V(343) = V_USER(640)
  V(201) = V_USER(641)
  V(699) = V_USER(642)
  V(30) = V_USER(643)
  V(344) = V_USER(644)
  V(865) = V_USER(645)
  V(2) = V_USER(646)
  V(892) = V_USER(647)
  V(839) = V_USER(648)
  V(660) = V_USER(649)
  V(821) = V_USER(650)
  V(503) = V_USER(651)
  V(877) = V_USER(652)
  V(619) = V_USER(653)
  V(511) = V_USER(654)
  V(202) = V_USER(655)
  V(713) = V_USER(656)
  V(596) = V_USER(657)
  V(345) = V_USER(658)
  V(346) = V_USER(659)
  V(203) = V_USER(660)
  V(347) = V_USER(661)
  V(439) = V_USER(662)
  V(204) = V_USER(663)
  V(348) = V_USER(664)
  V(440) = V_USER(665)
  V(746) = V_USER(666)
  V(504) = V_USER(667)
  V(71) = V_USER(668)
  V(663) = V_USER(669)
  V(837) = V_USER(670)
  V(557) = V_USER(671)
  V(767) = V_USER(672)
  V(349) = V_USER(673)
  V(891) = V_USER(674)
  V(245) = V_USER(675)
  V(350) = V_USER(676)
  V(505) = V_USER(677)
  V(441) = V_USER(678)
  V(664) = V_USER(679)
  V(749) = V_USER(680)
  V(863) = V_USER(681)
  V(351) = V_USER(682)
  V(352) = V_USER(683)
  V(246) = V_USER(684)
  V(353) = V_USER(685)
  V(740) = V_USER(686)
  V(129) = V_USER(687)
  V(560) = V_USER(688)
  V(793) = V_USER(689)
  V(354) = V_USER(690)
  V(130) = V_USER(691)
  V(624) = V_USER(692)
  V(72) = V_USER(693)
  V(444) = V_USER(694)
  V(506) = V_USER(695)
  V(355) = V_USER(696)
  V(206) = V_USER(697)
  V(657) = V_USER(698)
  V(890) = V_USER(699)
  V(247) = V_USER(700)
  V(562) = V_USER(701)
  V(840) = V_USER(702)
  V(867) = V_USER(703)
  V(563) = V_USER(704)
  V(248) = V_USER(705)
  V(446) = V_USER(706)
  V(823) = V_USER(707)
  V(702) = V_USER(708)
  V(357) = V_USER(709)
  V(358) = V_USER(710)
  V(703) = V_USER(711)
  V(447) = V_USER(712)
  V(359) = V_USER(713)
  V(12) = V_USER(714)
  V(587) = V_USER(715)
  V(334) = V_USER(716)
  V(73) = V_USER(717)
  V(792) = V_USER(718)
  V(737) = V_USER(719)
  V(819) = V_USER(720)
  V(815) = V_USER(721)
  V(75) = V_USER(722)
  V(761) = V_USER(723)
  V(508) = V_USER(724)
  V(666) = V_USER(725)
  V(362) = V_USER(726)
  V(76) = V_USER(727)
  V(364) = V_USER(728)
  V(841) = V_USER(729)
  V(544) = V_USER(730)
  V(207) = V_USER(731)
  V(600) = V_USER(732)
  V(449) = V_USER(733)
  V(613) = V_USER(734)
  V(627) = V_USER(735)
  V(208) = V_USER(736)
  V(365) = V_USER(737)
  V(450) = V_USER(738)
  V(784) = V_USER(739)
  V(693) = V_USER(740)
  V(756) = V_USER(741)
  V(74) = V_USER(742)
  V(820) = V_USER(743)
  V(209) = V_USER(744)
  V(650) = V_USER(745)
  V(131) = V_USER(746)
  V(777) = V_USER(747)
  V(846) = V_USER(748)
  V(249) = V_USER(749)
  V(765) = V_USER(750)
  V(366) = V_USER(751)
  V(671) = V_USER(752)
  V(672) = V_USER(753)
  V(825) = V_USER(754)
  V(367) = V_USER(755)
  V(77) = V_USER(756)
  V(565) = V_USER(757)
  V(211) = V_USER(758)
  V(451) = V_USER(759)
  V(212) = V_USER(760)
  V(628) = V_USER(761)
  V(733) = V_USER(762)
  V(452) = V_USER(763)
  V(845) = V_USER(764)
  V(369) = V_USER(765)
  V(614) = V_USER(766)
  V(213) = V_USER(767)
  V(747) = V_USER(768)
  V(78) = V_USER(769)
  V(370) = V_USER(770)
  V(809) = V_USER(771)
  V(79) = V_USER(772)
  V(707) = V_USER(773)
  V(603) = V_USER(774)
  V(827) = V_USER(775)
  V(372) = V_USER(776)
  V(736) = V_USER(777)
  V(454) = V_USER(778)
  V(31) = V_USER(779)
  V(373) = V_USER(780)
  V(455) = V_USER(781)
  V(566) = V_USER(782)
  V(695) = V_USER(783)
  V(888) = V_USER(784)
  V(510) = V_USER(785)
  V(456) = V_USER(786)
  V(457) = V_USER(787)
  V(512) = V_USER(788)
  V(80) = V_USER(789)
  V(214) = V_USER(790)
  V(32) = V_USER(791)
  V(458) = V_USER(792)
  V(82) = V_USER(793)
  V(132) = V_USER(794)
  V(459) = V_USER(795)
  V(215) = V_USER(796)
  V(726) = V_USER(797)
  V(390) = V_USER(798)
  V(750) = V_USER(799)
  V(271) = V_USER(800)
  V(488) = V_USER(801)
  V(829) = V_USER(802)
  V(216) = V_USER(803)
  V(569) = V_USER(804)
  V(277) = V_USER(805)
  V(571) = V_USER(806)
  V(635) = V_USER(807)
  V(217) = V_USER(808)
  V(861) = V_USER(809)
  V(771) = V_USER(810)
  V(709) = V_USER(811)
  V(462) = V_USER(812)
  V(218) = V_USER(813)
  V(697) = V_USER(814)
  V(546) = V_USER(815)
  V(219) = V_USER(816)
  V(790) = V_USER(817)
  V(41) = V_USER(818)
  V(220) = V_USER(819)
  V(33) = V_USER(820)
  V(222) = V_USER(821)
  V(465) = V_USER(822)
  V(807) = V_USER(823)
  V(710) = V_USER(824)
  V(794) = V_USER(825)
  V(466) = V_USER(826)
  V(606) = V_USER(827)
  V(572) = V_USER(828)
  V(377) = V_USER(829)
  V(515) = V_USER(830)
  V(83) = V_USER(831)
  V(378) = V_USER(832)
  V(223) = V_USER(833)
  V(379) = V_USER(834)
  V(516) = V_USER(835)
  V(468) = V_USER(836)
  V(638) = V_USER(837)
  V(469) = V_USER(838)
  V(639) = V_USER(839)
  V(380) = V_USER(840)
  V(640) = V_USER(841)
  V(656) = V_USER(842)
  V(381) = V_USER(843)
  V(894) = V_USER(844)
  V(590) = V_USER(845)
  V(382) = V_USER(846)
  V(224) = V_USER(847)
  V(836) = V_USER(848)
  V(225) = V_USER(849)
  V(226) = V_USER(850)
  V(866) = V_USER(851)
  V(34) = V_USER(852)
  V(227) = V_USER(853)
  V(830) = V_USER(854)
  V(518) = V_USER(855)
  V(228) = V_USER(856)
  V(84) = V_USER(857)
  V(35) = V_USER(858)
  V(473) = V_USER(859)
  V(474) = V_USER(860)
  V(591) = V_USER(861)
  V(133) = V_USER(862)
  V(475) = V_USER(863)
  V(476) = V_USER(864)
  V(875) = V_USER(865)
  V(229) = V_USER(866)
  V(584) = V_USER(867)
  V(758) = V_USER(868)
  V(478) = V_USER(869)
  V(659) = V_USER(870)
  V(649) = V_USER(871)
  V(42) = V_USER(872)
  V(479) = V_USER(873)
  V(521) = V_USER(874)
  V(688) = V_USER(875)
  V(611) = V_USER(876)
  V(85) = V_USER(877)
  V(480) = V_USER(878)
  V(848) = V_USER(879)
  V(612) = V_USER(880)
  V(549) = V_USER(881)
  V(523) = V_USER(882)
  V(581) = V_USER(883)
  V(9) = V_USER(884)
  V(37) = V_USER(885)
  V(86) = V_USER(886)
  V(230) = V_USER(887)
  V(10) = V_USER(888)
  V(1) = V_USER(889)
  V(3) = V_USER(890)
  V(4) = V_USER(891)
  V(5) = V_USER(892)
  V(6) = V_USER(893)
      
END SUBROUTINE Shuffle_user2kpp

! End of Shuffle_user2kpp function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Shuffle_kpp2user - function to restore concentrations from KPP to USER
!   Arguments :
!      V         - Concentrations of variable species (local)
!      V_USER    - Concentration of variable species in USER's order
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_kpp2user ( V, V_USER )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)

  V_USER(1) = V(252)
  V_USER(2) = V(437)
  V_USER(3) = V(481)
  V_USER(4) = V(482)
  V_USER(5) = V(38)
  V_USER(6) = V(385)
  V_USER(7) = V(818)
  V_USER(8) = V(687)
  V_USER(9) = V(36)
  V_USER(10) = V(662)
  V_USER(11) = V(402)
  V_USER(12) = V(360)
  V_USER(13) = V(198)
  V_USER(14) = V(256)
  V_USER(15) = V(185)
  V_USER(16) = V(617)
  V_USER(17) = V(96)
  V_USER(18) = V(886)
  V_USER(19) = V(162)
  V_USER(20) = V(60)
  V_USER(21) = V(625)
  V_USER(22) = V(787)
  V_USER(23) = V(394)
  V_USER(24) = V(292)
  V_USER(25) = V(295)
  V_USER(26) = V(412)
  V_USER(27) = V(331)
  V_USER(28) = V(553)
  V_USER(29) = V(13)
  V_USER(30) = V(70)
  V_USER(31) = V(748)
  V_USER(32) = V(615)
  V_USER(33) = V(221)
  V_USER(34) = V(517)
  V_USER(35) = V(540)
  V_USER(36) = V(689)
  V_USER(37) = V(802)
  V_USER(38) = V(384)
  V_USER(39) = V(319)
  V_USER(40) = V(49)
  V_USER(41) = V(513)
  V_USER(42) = V(610)
  V_USER(43) = V(730)
  V_USER(44) = V(391)
  V_USER(45) = V(242)
  V_USER(46) = V(770)
  V_USER(47) = V(323)
  V_USER(48) = V(243)
  V_USER(49) = V(502)
  V_USER(50) = V(654)
  V_USER(51) = V(460)
  V_USER(52) = V(14)
  V_USER(53) = V(81)
  V_USER(54) = V(769)
  V_USER(55) = V(700)
  V_USER(56) = V(111)
  V_USER(57) = V(448)
  V_USER(58) = V(279)
  V_USER(59) = V(165)
  V_USER(60) = V(166)
  V_USER(61) = V(167)
  V_USER(62) = V(302)
  V_USER(63) = V(241)
  V_USER(64) = V(123)
  V_USER(65) = V(124)
  V_USER(66) = V(646)
  V_USER(67) = V(336)
  V_USER(68) = V(669)
  V_USER(69) = V(679)
  V_USER(70) = V(435)
  V_USER(71) = V(893)
  V_USER(72) = V(205)
  V_USER(73) = V(361)
  V_USER(74) = V(734)
  V_USER(75) = V(665)
  V_USER(76) = V(363)
  V_USER(77) = V(250)
  V_USER(78) = V(588)
  V_USER(79) = V(453)
  V_USER(80) = V(567)
  V_USER(81) = V(393)
  V_USER(82) = V(374)
  V_USER(83) = V(371)
  V_USER(84) = V(745)
  V_USER(85) = V(522)
  V_USER(86) = V(575)
  V_USER(87) = V(438)
  V_USER(88) = V(43)
  V_USER(89) = V(728)
  V_USER(90) = V(442)
  V_USER(91) = V(568)
  V_USER(92) = V(817)
  V_USER(93) = V(69)
  V_USER(94) = V(232)
  V_USER(95) = V(658)
  V_USER(96) = V(297)
  V_USER(97) = V(314)
  V_USER(98) = V(673)
  V_USER(99) = V(340)
  V_USER(100) = V(578)
  V_USER(101) = V(791)
  V_USER(102) = V(432)
  V_USER(103) = V(601)
  V_USER(104) = V(260)
  V_USER(105) = V(265)
  V_USER(106) = V(152)
  V_USER(107) = V(153)
  V_USER(108) = V(643)
  V_USER(109) = V(550)
  V_USER(110) = V(881)
  V_USER(111) = V(87)
  V_USER(112) = V(683)
  V_USER(113) = V(44)
  V_USER(114) = V(386)
  V_USER(115) = V(852)
  V_USER(116) = V(174)
  V_USER(117) = V(303)
  V_USER(118) = V(532)
  V_USER(119) = V(88)
  V_USER(120) = V(45)
  V_USER(121) = V(184)
  V_USER(122) = V(621)
  V_USER(123) = V(15)
  V_USER(124) = V(417)
  V_USER(125) = V(191)
  V_USER(126) = V(680)
  V_USER(127) = V(722)
  V_USER(128) = V(89)
  V_USER(129) = V(90)
  V_USER(130) = V(443)
  V_USER(131) = V(210)
  V_USER(132) = V(91)
  V_USER(133) = V(609)
  V_USER(134) = V(396)
  V_USER(135) = V(92)
  V_USER(136) = V(93)
  V_USER(137) = V(291)
  V_USER(138) = V(755)
  V_USER(139) = V(799)
  V_USER(140) = V(744)
  V_USER(141) = V(524)
  V_USER(142) = V(94)
  V_USER(143) = V(253)
  V_USER(144) = V(95)
  V_USER(145) = V(134)
  V_USER(146) = V(816)
  V_USER(147) = V(387)
  V_USER(148) = V(605)
  V_USER(149) = V(514)
  V_USER(150) = V(264)
  V_USER(151) = V(414)
  V_USER(152) = V(16)
  V_USER(153) = V(859)
  V_USER(154) = V(574)
  V_USER(155) = V(423)
  V_USER(156) = V(236)
  V_USER(157) = V(486)
  V_USER(158) = V(275)
  V_USER(159) = V(631)
  V_USER(160) = V(760)
  V_USER(161) = V(655)
  V_USER(162) = V(548)
  V_USER(163) = V(641)
  V_USER(164) = V(135)
  V_USER(165) = V(690)
  V_USER(166) = V(239)
  V_USER(167) = V(289)
  V_USER(168) = V(554)
  V_USER(169) = V(582)
  V_USER(170) = V(880)
  V_USER(171) = V(803)
  V_USER(172) = V(17)
  V_USER(173) = V(298)
  V_USER(174) = V(583)
  V_USER(175) = V(685)
  V_USER(176) = V(757)
  V_USER(177) = V(623)
  V_USER(178) = V(97)
  V_USER(179) = V(315)
  V_USER(180) = V(538)
  V_USER(181) = V(46)
  V_USER(182) = V(39)
  V_USER(183) = V(415)
  V_USER(184) = V(98)
  V_USER(185) = V(742)
  V_USER(186) = V(579)
  V_USER(187) = V(670)
  V_USER(188) = V(418)
  V_USER(189) = V(47)
  V_USER(190) = V(48)
  V_USER(191) = V(696)
  V_USER(192) = V(684)
  V_USER(193) = V(828)
  V_USER(194) = V(500)
  V_USER(195) = V(40)
  V_USER(196) = V(424)
  V_USER(197) = V(99)
  V_USER(198) = V(530)
  V_USER(199) = V(50)
  V_USER(200) = V(342)
  V_USER(201) = V(434)
  V_USER(202) = V(882)
  V_USER(203) = V(835)
  V_USER(204) = V(706)
  V_USER(205) = V(811)
  V_USER(206) = V(356)
  V_USER(207) = V(762)
  V_USER(208) = V(851)
  V_USER(209) = V(100)
  V_USER(210) = V(725)
  V_USER(211) = V(536)
  V_USER(212) = V(674)
  V_USER(213) = V(616)
  V_USER(214) = V(136)
  V_USER(215) = V(375)
  V_USER(216) = V(51)
  V_USER(217) = V(738)
  V_USER(218) = V(376)
  V_USER(219) = V(764)
  V_USER(220) = V(463)
  V_USER(221) = V(489)
  V_USER(222) = V(464)
  V_USER(223) = V(648)
  V_USER(224) = V(858)
  V_USER(225) = V(714)
  V_USER(226) = V(754)
  V_USER(227) = V(471)
  V_USER(228) = V(251)
  V_USER(229) = V(477)
  V_USER(230) = V(383)
  V_USER(231) = V(137)
  V_USER(232) = V(724)
  V_USER(233) = V(461)
  V_USER(234) = V(138)
  V_USER(235) = V(589)
  V_USER(236) = V(436)
  V_USER(237) = V(445)
  V_USER(238) = V(535)
  V_USER(239) = V(804)
  V_USER(240) = V(231)
  V_USER(241) = V(307)
  V_USER(242) = V(526)
  V_USER(243) = V(139)
  V_USER(244) = V(729)
  V_USER(245) = V(487)
  V_USER(246) = V(140)
  V_USER(247) = V(692)
  V_USER(248) = V(779)
  V_USER(249) = V(810)
  V_USER(250) = V(368)
  V_USER(251) = V(472)
  V_USER(252) = V(141)
  V_USER(253) = V(533)
  V_USER(254) = V(499)
  V_USER(255) = V(142)
  V_USER(256) = V(143)
  V_USER(257) = V(869)
  V_USER(258) = V(101)
  V_USER(259) = V(144)
  V_USER(260) = V(145)
  V_USER(261) = V(676)
  V_USER(262) = V(883)
  V_USER(263) = V(717)
  V_USER(264) = V(407)
  V_USER(265) = V(661)
  V_USER(266) = V(850)
  V_USER(267) = V(686)
  V_USER(268) = V(254)
  V_USER(269) = V(552)
  V_USER(270) = V(783)
  V_USER(271) = V(720)
  V_USER(272) = V(255)
  V_USER(273) = V(102)
  V_USER(274) = V(52)
  V_USER(275) = V(257)
  V_USER(276) = V(146)
  V_USER(277) = V(233)
  V_USER(278) = V(870)
  V_USER(279) = V(637)
  V_USER(280) = V(467)
  V_USER(281) = V(258)
  V_USER(282) = V(259)
  V_USER(283) = V(701)
  V_USER(284) = V(53)
  V_USER(285) = V(103)
  V_USER(286) = V(519)
  V_USER(287) = V(104)
  V_USER(288) = V(718)
  V_USER(289) = V(54)
  V_USER(290) = V(868)
  V_USER(291) = V(838)
  V_USER(292) = V(55)
  V_USER(293) = V(595)
  V_USER(294) = V(403)
  V_USER(295) = V(872)
  V_USER(296) = V(261)
  V_USER(297) = V(147)
  V_USER(298) = V(708)
  V_USER(299) = V(148)
  V_USER(300) = V(149)
  V_USER(301) = V(262)
  V_USER(302) = V(234)
  V_USER(303) = V(406)
  V_USER(304) = V(263)
  V_USER(305) = V(580)
  V_USER(306) = V(150)
  V_USER(307) = V(408)
  V_USER(308) = V(105)
  V_USER(309) = V(542)
  V_USER(310) = V(626)
  V_USER(311) = V(884)
  V_USER(312) = V(812)
  V_USER(313) = V(491)
  V_USER(314) = V(576)
  V_USER(315) = V(547)
  V_USER(316) = V(151)
  V_USER(317) = V(106)
  V_USER(318) = V(107)
  V_USER(319) = V(154)
  V_USER(320) = V(483)
  V_USER(321) = V(585)
  V_USER(322) = V(266)
  V_USER(323) = V(716)
  V_USER(324) = V(108)
  V_USER(325) = V(109)
  V_USER(326) = V(235)
  V_USER(327) = V(267)
  V_USER(328) = V(814)
  V_USER(329) = V(620)
  V_USER(330) = V(268)
  V_USER(331) = V(269)
  V_USER(332) = V(110)
  V_USER(333) = V(763)
  V_USER(334) = V(651)
  V_USER(335) = V(698)
  V_USER(336) = V(805)
  V_USER(337) = V(155)
  V_USER(338) = V(849)
  V_USER(339) = V(270)
  V_USER(340) = V(427)
  V_USER(341) = V(272)
  V_USER(342) = V(429)
  V_USER(343) = V(273)
  V_USER(344) = V(156)
  V_USER(345) = V(56)
  V_USER(346) = V(157)
  V_USER(347) = V(586)
  V_USER(348) = V(274)
  V_USER(349) = V(847)
  V_USER(350) = V(622)
  V_USER(351) = V(158)
  V_USER(352) = V(824)
  V_USER(353) = V(832)
  V_USER(354) = V(598)
  V_USER(355) = V(237)
  V_USER(356) = V(507)
  V_USER(357) = V(691)
  V_USER(358) = V(599)
  V_USER(359) = V(753)
  V_USER(360) = V(57)
  V_USER(361) = V(276)
  V_USER(362) = V(564)
  V_USER(363) = V(577)
  V_USER(364) = V(238)
  V_USER(365) = V(732)
  V_USER(366) = V(735)
  V_USER(367) = V(18)
  V_USER(368) = V(644)
  V_USER(369) = V(789)
  V_USER(370) = V(278)
  V_USER(371) = V(58)
  V_USER(372) = V(159)
  V_USER(373) = V(831)
  V_USER(374) = V(160)
  V_USER(375) = V(834)
  V_USER(376) = V(112)
  V_USER(377) = V(280)
  V_USER(378) = V(161)
  V_USER(379) = V(878)
  V_USER(380) = V(470)
  V_USER(381) = V(19)
  V_USER(382) = V(163)
  V_USER(383) = V(164)
  V_USER(384) = V(873)
  V_USER(385) = V(59)
  V_USER(386) = V(281)
  V_USER(387) = V(20)
  V_USER(388) = V(766)
  V_USER(389) = V(425)
  V_USER(390) = V(874)
  V_USER(391) = V(282)
  V_USER(392) = V(283)
  V_USER(393) = V(558)
  V_USER(394) = V(113)
  V_USER(395) = V(555)
  V_USER(396) = V(21)
  V_USER(397) = V(496)
  V_USER(398) = V(392)
  V_USER(399) = V(593)
  V_USER(400) = V(531)
  V_USER(401) = V(22)
  V_USER(402) = V(284)
  V_USER(403) = V(862)
  V_USER(404) = V(114)
  V_USER(405) = V(285)
  V_USER(406) = V(23)
  V_USER(407) = V(286)
  V_USER(408) = V(395)
  V_USER(409) = V(798)
  V_USER(410) = V(287)
  V_USER(411) = V(776)
  V_USER(412) = V(678)
  V_USER(413) = V(788)
  V_USER(414) = V(115)
  V_USER(415) = V(721)
  V_USER(416) = V(774)
  V_USER(417) = V(397)
  V_USER(418) = V(541)
  V_USER(419) = V(527)
  V_USER(420) = V(860)
  V_USER(421) = V(288)
  V_USER(422) = V(398)
  V_USER(423) = V(889)
  V_USER(424) = V(61)
  V_USER(425) = V(759)
  V_USER(426) = V(399)
  V_USER(427) = V(290)
  V_USER(428) = V(168)
  V_USER(429) = V(169)
  V_USER(430) = V(240)
  V_USER(431) = V(24)
  V_USER(432) = V(170)
  V_USER(433) = V(705)
  V_USER(434) = V(778)
  V_USER(435) = V(400)
  V_USER(436) = V(401)
  V_USER(437) = V(293)
  V_USER(438) = V(8)
  V_USER(439) = V(822)
  V_USER(440) = V(854)
  V_USER(441) = V(11)
  V_USER(442) = V(559)
  V_USER(443) = V(739)
  V_USER(444) = V(561)
  V_USER(445) = V(879)
  V_USER(446) = V(534)
  V_USER(447) = V(294)
  V_USER(448) = V(25)
  V_USER(449) = V(545)
  V_USER(450) = V(652)
  V_USER(451) = V(537)
  V_USER(452) = V(602)
  V_USER(453) = V(296)
  V_USER(454) = V(509)
  V_USER(455) = V(171)
  V_USER(456) = V(604)
  V_USER(457) = V(172)
  V_USER(458) = V(173)
  V_USER(459) = V(632)
  V_USER(460) = V(855)
  V_USER(461) = V(570)
  V_USER(462) = V(299)
  V_USER(463) = V(404)
  V_USER(464) = V(116)
  V_USER(465) = V(300)
  V_USER(466) = V(301)
  V_USER(467) = V(573)
  V_USER(468) = V(405)
  V_USER(469) = V(607)
  V_USER(470) = V(539)
  V_USER(471) = V(795)
  V_USER(472) = V(62)
  V_USER(473) = V(608)
  V_USER(474) = V(813)
  V_USER(475) = V(797)
  V_USER(476) = V(117)
  V_USER(477) = V(304)
  V_USER(478) = V(305)
  V_USER(479) = V(306)
  V_USER(480) = V(781)
  V_USER(481) = V(642)
  V_USER(482) = V(741)
  V_USER(483) = V(727)
  V_USER(484) = V(175)
  V_USER(485) = V(63)
  V_USER(486) = V(409)
  V_USER(487) = V(176)
  V_USER(488) = V(844)
  V_USER(489) = V(864)
  V_USER(490) = V(410)
  V_USER(491) = V(411)
  V_USER(492) = V(833)
  V_USER(493) = V(490)
  V_USER(494) = V(856)
  V_USER(495) = V(308)
  V_USER(496) = V(775)
  V_USER(497) = V(309)
  V_USER(498) = V(645)
  V_USER(499) = V(310)
  V_USER(500) = V(843)
  V_USER(501) = V(311)
  V_USER(502) = V(313)
  V_USER(503) = V(118)
  V_USER(504) = V(876)
  V_USER(505) = V(177)
  V_USER(506) = V(492)
  V_USER(507) = V(773)
  V_USER(508) = V(493)
  V_USER(509) = V(26)
  V_USER(510) = V(871)
  V_USER(511) = V(178)
  V_USER(512) = V(413)
  V_USER(513) = V(786)
  V_USER(514) = V(800)
  V_USER(515) = V(179)
  V_USER(516) = V(180)
  V_USER(517) = V(316)
  V_USER(518) = V(826)
  V_USER(519) = V(317)
  V_USER(520) = V(318)
  V_USER(521) = V(181)
  V_USER(522) = V(182)
  V_USER(523) = V(183)
  V_USER(524) = V(772)
  V_USER(525) = V(556)
  V_USER(526) = V(119)
  V_USER(527) = V(808)
  V_USER(528) = V(752)
  V_USER(529) = V(653)
  V_USER(530) = V(320)
  V_USER(531) = V(321)
  V_USER(532) = V(857)
  V_USER(533) = V(525)
  V_USER(534) = V(120)
  V_USER(535) = V(667)
  V_USER(536) = V(121)
  V_USER(537) = V(520)
  V_USER(538) = V(322)
  V_USER(539) = V(712)
  V_USER(540) = V(715)
  V_USER(541) = V(122)
  V_USER(542) = V(64)
  V_USER(543) = V(312)
  V_USER(544) = V(668)
  V_USER(545) = V(494)
  V_USER(546) = V(416)
  V_USER(547) = V(186)
  V_USER(548) = V(768)
  V_USER(549) = V(495)
  V_USER(550) = V(187)
  V_USER(551) = V(65)
  V_USER(552) = V(630)
  V_USER(553) = V(647)
  V_USER(554) = V(677)
  V_USER(555) = V(751)
  V_USER(556) = V(188)
  V_USER(557) = V(694)
  V_USER(558) = V(597)
  V_USER(559) = V(189)
  V_USER(560) = V(190)
  V_USER(561) = V(388)
  V_USER(562) = V(497)
  V_USER(563) = V(743)
  V_USER(564) = V(723)
  V_USER(565) = V(419)
  V_USER(566) = V(498)
  V_USER(567) = V(125)
  V_USER(568) = V(681)
  V_USER(569) = V(633)
  V_USER(570) = V(731)
  V_USER(571) = V(634)
  V_USER(572) = V(192)
  V_USER(573) = V(484)
  V_USER(574) = V(801)
  V_USER(575) = V(782)
  V_USER(576) = V(420)
  V_USER(577) = V(324)
  V_USER(578) = V(325)
  V_USER(579) = V(326)
  V_USER(580) = V(433)
  V_USER(581) = V(421)
  V_USER(582) = V(66)
  V_USER(583) = V(636)
  V_USER(584) = V(842)
  V_USER(585) = V(853)
  V_USER(586) = V(193)
  V_USER(587) = V(796)
  V_USER(588) = V(629)
  V_USER(589) = V(327)
  V_USER(590) = V(887)
  V_USER(591) = V(328)
  V_USER(592) = V(244)
  V_USER(593) = V(675)
  V_USER(594) = V(543)
  V_USER(595) = V(592)
  V_USER(596) = V(329)
  V_USER(597) = V(719)
  V_USER(598) = V(422)
  V_USER(599) = V(551)
  V_USER(600) = V(330)
  V_USER(601) = V(528)
  V_USER(602) = V(194)
  V_USER(603) = V(27)
  V_USER(604) = V(332)
  V_USER(605) = V(333)
  V_USER(606) = V(28)
  V_USER(607) = V(335)
  V_USER(608) = V(67)
  V_USER(609) = V(337)
  V_USER(610) = V(501)
  V_USER(611) = V(780)
  V_USER(612) = V(338)
  V_USER(613) = V(68)
  V_USER(614) = V(195)
  V_USER(615) = V(126)
  V_USER(616) = V(529)
  V_USER(617) = V(196)
  V_USER(618) = V(389)
  V_USER(619) = V(426)
  V_USER(620) = V(711)
  V_USER(621) = V(339)
  V_USER(622) = V(197)
  V_USER(623) = V(682)
  V_USER(624) = V(885)
  V_USER(625) = V(127)
  V_USER(626) = V(704)
  V_USER(627) = V(341)
  V_USER(628) = V(29)
  V_USER(629) = V(199)
  V_USER(630) = V(428)
  V_USER(631) = V(618)
  V_USER(632) = V(128)
  V_USER(633) = V(200)
  V_USER(634) = V(785)
  V_USER(635) = V(485)
  V_USER(636) = V(806)
  V_USER(637) = V(594)
  V_USER(638) = V(430)
  V_USER(639) = V(431)
  V_USER(640) = V(343)
  V_USER(641) = V(201)
  V_USER(642) = V(699)
  V_USER(643) = V(30)
  V_USER(644) = V(344)
  V_USER(645) = V(865)
  V_USER(646) = V(2)
  V_USER(647) = V(892)
  V_USER(648) = V(839)
  V_USER(649) = V(660)
  V_USER(650) = V(821)
  V_USER(651) = V(503)
  V_USER(652) = V(877)
  V_USER(653) = V(619)
  V_USER(654) = V(511)
  V_USER(655) = V(202)
  V_USER(656) = V(713)
  V_USER(657) = V(596)
  V_USER(658) = V(345)
  V_USER(659) = V(346)
  V_USER(660) = V(203)
  V_USER(661) = V(347)
  V_USER(662) = V(439)
  V_USER(663) = V(204)
  V_USER(664) = V(348)
  V_USER(665) = V(440)
  V_USER(666) = V(746)
  V_USER(667) = V(504)
  V_USER(668) = V(71)
  V_USER(669) = V(663)
  V_USER(670) = V(837)
  V_USER(671) = V(557)
  V_USER(672) = V(767)
  V_USER(673) = V(349)
  V_USER(674) = V(891)
  V_USER(675) = V(245)
  V_USER(676) = V(350)
  V_USER(677) = V(505)
  V_USER(678) = V(441)
  V_USER(679) = V(664)
  V_USER(680) = V(749)
  V_USER(681) = V(863)
  V_USER(682) = V(351)
  V_USER(683) = V(352)
  V_USER(684) = V(246)
  V_USER(685) = V(353)
  V_USER(686) = V(740)
  V_USER(687) = V(129)
  V_USER(688) = V(560)
  V_USER(689) = V(793)
  V_USER(690) = V(354)
  V_USER(691) = V(130)
  V_USER(692) = V(624)
  V_USER(693) = V(72)
  V_USER(694) = V(444)
  V_USER(695) = V(506)
  V_USER(696) = V(355)
  V_USER(697) = V(206)
  V_USER(698) = V(657)
  V_USER(699) = V(890)
  V_USER(700) = V(247)
  V_USER(701) = V(562)
  V_USER(702) = V(840)
  V_USER(703) = V(867)
  V_USER(704) = V(563)
  V_USER(705) = V(248)
  V_USER(706) = V(446)
  V_USER(707) = V(823)
  V_USER(708) = V(702)
  V_USER(709) = V(357)
  V_USER(710) = V(358)
  V_USER(711) = V(703)
  V_USER(712) = V(447)
  V_USER(713) = V(359)
  V_USER(714) = V(12)
  V_USER(715) = V(587)
  V_USER(716) = V(334)
  V_USER(717) = V(73)
  V_USER(718) = V(792)
  V_USER(719) = V(737)
  V_USER(720) = V(819)
  V_USER(721) = V(815)
  V_USER(722) = V(75)
  V_USER(723) = V(761)
  V_USER(724) = V(508)
  V_USER(725) = V(666)
  V_USER(726) = V(362)
  V_USER(727) = V(76)
  V_USER(728) = V(364)
  V_USER(729) = V(841)
  V_USER(730) = V(544)
  V_USER(731) = V(207)
  V_USER(732) = V(600)
  V_USER(733) = V(449)
  V_USER(734) = V(613)
  V_USER(735) = V(627)
  V_USER(736) = V(208)
  V_USER(737) = V(365)
  V_USER(738) = V(450)
  V_USER(739) = V(784)
  V_USER(740) = V(693)
  V_USER(741) = V(756)
  V_USER(742) = V(74)
  V_USER(743) = V(820)
  V_USER(744) = V(209)
  V_USER(745) = V(650)
  V_USER(746) = V(131)
  V_USER(747) = V(777)
  V_USER(748) = V(846)
  V_USER(749) = V(249)
  V_USER(750) = V(765)
  V_USER(751) = V(366)
  V_USER(752) = V(671)
  V_USER(753) = V(672)
  V_USER(754) = V(825)
  V_USER(755) = V(367)
  V_USER(756) = V(77)
  V_USER(757) = V(565)
  V_USER(758) = V(211)
  V_USER(759) = V(451)
  V_USER(760) = V(212)
  V_USER(761) = V(628)
  V_USER(762) = V(733)
  V_USER(763) = V(452)
  V_USER(764) = V(845)
  V_USER(765) = V(369)
  V_USER(766) = V(614)
  V_USER(767) = V(213)
  V_USER(768) = V(747)
  V_USER(769) = V(78)
  V_USER(770) = V(370)
  V_USER(771) = V(809)
  V_USER(772) = V(79)
  V_USER(773) = V(707)
  V_USER(774) = V(603)
  V_USER(775) = V(827)
  V_USER(776) = V(372)
  V_USER(777) = V(736)
  V_USER(778) = V(454)
  V_USER(779) = V(31)
  V_USER(780) = V(373)
  V_USER(781) = V(455)
  V_USER(782) = V(566)
  V_USER(783) = V(695)
  V_USER(784) = V(888)
  V_USER(785) = V(510)
  V_USER(786) = V(456)
  V_USER(787) = V(457)
  V_USER(788) = V(512)
  V_USER(789) = V(80)
  V_USER(790) = V(214)
  V_USER(791) = V(32)
  V_USER(792) = V(458)
  V_USER(793) = V(82)
  V_USER(794) = V(132)
  V_USER(795) = V(459)
  V_USER(796) = V(215)
  V_USER(797) = V(726)
  V_USER(798) = V(390)
  V_USER(799) = V(750)
  V_USER(800) = V(271)
  V_USER(801) = V(488)
  V_USER(802) = V(829)
  V_USER(803) = V(216)
  V_USER(804) = V(569)
  V_USER(805) = V(277)
  V_USER(806) = V(571)
  V_USER(807) = V(635)
  V_USER(808) = V(217)
  V_USER(809) = V(861)
  V_USER(810) = V(771)
  V_USER(811) = V(709)
  V_USER(812) = V(462)
  V_USER(813) = V(218)
  V_USER(814) = V(697)
  V_USER(815) = V(546)
  V_USER(816) = V(219)
  V_USER(817) = V(790)
  V_USER(818) = V(41)
  V_USER(819) = V(220)
  V_USER(820) = V(33)
  V_USER(821) = V(222)
  V_USER(822) = V(465)
  V_USER(823) = V(807)
  V_USER(824) = V(710)
  V_USER(825) = V(794)
  V_USER(826) = V(466)
  V_USER(827) = V(606)
  V_USER(828) = V(572)
  V_USER(829) = V(377)
  V_USER(830) = V(515)
  V_USER(831) = V(83)
  V_USER(832) = V(378)
  V_USER(833) = V(223)
  V_USER(834) = V(379)
  V_USER(835) = V(516)
  V_USER(836) = V(468)
  V_USER(837) = V(638)
  V_USER(838) = V(469)
  V_USER(839) = V(639)
  V_USER(840) = V(380)
  V_USER(841) = V(640)
  V_USER(842) = V(656)
  V_USER(843) = V(381)
  V_USER(844) = V(894)
  V_USER(845) = V(590)
  V_USER(846) = V(382)
  V_USER(847) = V(224)
  V_USER(848) = V(836)
  V_USER(849) = V(225)
  V_USER(850) = V(226)
  V_USER(851) = V(866)
  V_USER(852) = V(34)
  V_USER(853) = V(227)
  V_USER(854) = V(830)
  V_USER(855) = V(518)
  V_USER(856) = V(228)
  V_USER(857) = V(84)
  V_USER(858) = V(35)
  V_USER(859) = V(473)
  V_USER(860) = V(474)
  V_USER(861) = V(591)
  V_USER(862) = V(133)
  V_USER(863) = V(475)
  V_USER(864) = V(476)
  V_USER(865) = V(875)
  V_USER(866) = V(229)
  V_USER(867) = V(584)
  V_USER(868) = V(758)
  V_USER(869) = V(478)
  V_USER(870) = V(659)
  V_USER(871) = V(649)
  V_USER(872) = V(42)
  V_USER(873) = V(479)
  V_USER(874) = V(521)
  V_USER(875) = V(688)
  V_USER(876) = V(611)
  V_USER(877) = V(85)
  V_USER(878) = V(480)
  V_USER(879) = V(848)
  V_USER(880) = V(612)
  V_USER(881) = V(549)
  V_USER(882) = V(523)
  V_USER(883) = V(581)
  V_USER(884) = V(9)
  V_USER(885) = V(37)
  V_USER(886) = V(86)
  V_USER(887) = V(230)
  V_USER(888) = V(10)
  V_USER(889) = V(1)
  V_USER(890) = V(3)
  V_USER(891) = V(4)
  V_USER(892) = V(5)
  V_USER(893) = V(6)
      
END SUBROUTINE Shuffle_kpp2user

! End of Shuffle_kpp2user function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! GetMass - compute total mass of selected atoms
!   Arguments :
!      CL        - Concentration of all species (local)
!      Mass      - value of mass balance
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE GetMass ( CL, Mass )

! CL - Concentration of all species (local)
  REAL(kind=dp) :: CL(NSPEC)
! Mass - value of mass balance
  REAL(kind=dp) :: Mass(1)

      
END SUBROUTINE GetMass

! End of GetMass function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE model_Util

