! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : model_Rates.f90
! Time                 : Thu Feb 16 17:13:45 2017
! Working directory    : /work/home/dp626/DSMACC-testing
! Equation file        : model.kpp
! Output root filename : model
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE model_Rates

  USE model_Parameters
  USE model_Global
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR        

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0           
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )              
   END FUNCTION ARR2          

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(kind=dp) K0,K2,K3            
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2) 
      REAL A1, C1, A2, C2
      REAL(kind=dp) K1, K2      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3 

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1     
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL, INTENT(IN) :: n         ! exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL, INTENT(IN) :: m         ! exponent for high pressure limit
    REAL, INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions


! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE model_Parameters
      !USE model_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST



USE constants
RO2 = 0&
+C(ind_CH3CO3)&
+C(ind_CH3O2)&
+C(ind_RU14O2)&
+C(ind_RU10O2)&
+C(ind_HOCH2CO3)&
+C(ind_RU12O2)
CALL mcm_constants(time, temp, M, N2, O2, RO2, H2O)

! End INLINED RCONST

  RCONST(1) = (6.00E-34*O2*O2*((TEMP/300)**-2.6)+5.60E-34*O2*N2*((TEMP/300)**-2.6))
  RCONST(2) = (8.00E-12*EXP(-2060/TEMP))
  RCONST(3) = (KMT01)
  RCONST(4) = (5.50E-12*EXP(188/TEMP))
  RCONST(5) = (KMT02)
  RCONST(6) = (3.20E-11*O2*EXP(67/TEMP)+2.0E-11*N2*EXP(130/TEMP))
  RCONST(7) = (1.40E-12*EXP(-1310/TEMP))
  RCONST(8) = (1.40E-13*EXP(-2470/TEMP))
  RCONST(9) = (3.30E-39*EXP(530/TEMP)*O2)
  RCONST(10) = (1.80E-11*EXP(110/TEMP))
  RCONST(11) = (4.50E-14*EXP(-1260/TEMP))
  RCONST(12) = (KMT03)
  RCONST(13) = (KMT04)
  RCONST(14) = (2.14E-10*H2O)
  RCONST(15) = (1.70E-12*EXP(-940/TEMP))
  RCONST(16) = (7.70E-12*EXP(-2100/TEMP))
  RCONST(17) = (KMT05)
  RCONST(18) = (2.90E-12*EXP(-160/TEMP))
  RCONST(19) = (2.03E-16*((TEMP/300)**4.57)*EXP(693/TEMP))
  RCONST(20) = (4.80E-11*EXP(250/TEMP))
  RCONST(21) = (2.20E-13*KMT06*EXP(600/TEMP)+1.90E-33*M*KMT06*EXP(980/TEMP))
  RCONST(22) = (KMT07)
  RCONST(23) = (KMT08)
! RCONST(24) = constant rate coefficient
  RCONST(25) = (3.45E-12*EXP(270/TEMP))
  RCONST(26) = (KMT09)
  RCONST(27) = (KMT10)
  RCONST(28) = (3.20E-13*EXP(690/TEMP))
! RCONST(29) = constant rate coefficient
  RCONST(30) = (2.50E-12*EXP(260/TEMP))
  RCONST(31) = (KMT11)
  RCONST(32) = (4.00E-32*EXP(-1000/TEMP)*M)
  RCONST(33) = (KMT12)
  RCONST(34) = (1.30E-12*EXP(-330/TEMP)*O2)
  RCONST(35) = (J(1))
  RCONST(36) = (J(2))
  RCONST(37) = (J(3))
  RCONST(38) = (J(4))
  RCONST(39) = (J(5))
  RCONST(40) = (J(6))
  RCONST(41) = (J(7))
  RCONST(42) = (J(8))
  RCONST(43) = (1.20D-15*H2O)
! RCONST(44) = constant rate coefficient
! RCONST(45) = constant rate coefficient
  RCONST(46) = (6.01D-18*TEMP**2*EXP(170/TEMP))
  RCONST(47) = (J(12))
  RCONST(48) = (1.20D-14*TEMP*EXP(287/TEMP))
  RCONST(49) = (J(11))
  RCONST(50) = (2.54D-11*EXP(410/TEMP))
  RCONST(51) = (7.86D-15*EXP(-1913/TEMP)*0.27)
  RCONST(52) = (7.86D-15*EXP(-1913/TEMP)*0.73)
  RCONST(53) = (4.50D-13)
  RCONST(54) = (1.00D-11*RO2)
  RCONST(55) = (KFPAN)
  RCONST(56) = (KAPHO2)
  RCONST(57) = (KAPNO)
  RCONST(58) = (1.82D-13*EXP(416/TEMP)*0.335*RO2)
  RCONST(59) = (3.00D-12*EXP(280/TEMP)*0.001)
  RCONST(60) = (1.82D-13*EXP(416/TEMP)*0.335*RO2)
  RCONST(61) = (1.82D-13*EXP(416/TEMP)*0.33*RO2)
  RCONST(62) = (4.10D-13*EXP(790/TEMP))
  RCONST(63) = (3.00D-12*EXP(280/TEMP)*0.999)
  RCONST(64) = (KRO2NO*0.100)
  RCONST(65) = (KRO2HO2*0.770)
  RCONST(66) = (1.71D-12*RO2*0.252)
  RCONST(67) = (KRO2NO*0.900*0.252)
  RCONST(68) = (1.71D-12*RO2*0.748)
  RCONST(69) = (KRO2NO*0.900*0.748)
  RCONST(70) = (2.50D-11)
  RCONST(71) = (2.85D-18*0.59)
  RCONST(72) = (J(18)*2)
  RCONST(73) = (2.85D-18*0.41)
  RCONST(74) = (1.00D-11)
  RCONST(75) = (J(15))
  RCONST(76) = (KBPAN)
  RCONST(77) = (9.50D-13*EXP(-650/TEMP))
  RCONST(78) = (J(41))
  RCONST(79) = (3.70D-12)
  RCONST(80) = (1.00D-14*EXP(1060/TEMP))
  RCONST(81) = (J(51))
  RCONST(82) = (1.90D-12*EXP(190/TEMP))
  RCONST(83) = (1.00D-12*EXP(190/TEMP))
  RCONST(84) = (J(41))
  RCONST(85) = (1.72D-11)
  RCONST(86) = (J(34))
  RCONST(87) = (5.55D-11)
  RCONST(88) = (7.51D-11)
  RCONST(89) = (J(41)*0.252)
  RCONST(90) = (J(41)*0.748)
  RCONST(91) = (4.52D-11)
  RCONST(92) = (2.40D-17*0.89)
  RCONST(93) = (2.40D-17*0.11)
  RCONST(94) = (J(18)*2)
  RCONST(95) = (KFPAN*0.041)
  RCONST(96) = (2.00D-12*RO2*0.5)
  RCONST(97) = (KRO2HO2*0.625)
  RCONST(98) = (2.00D-12*RO2*0.3)
  RCONST(99) = (2.00D-12*RO2*0.2)
  RCONST(100) = (KRO2NO*0.5)
  RCONST(101) = (KRO2NO*0.2)
  RCONST(102) = (KRO2NO*0.3)
  RCONST(103) = (KAPHO2)
  RCONST(104) = (1.00D-11*RO2)
  RCONST(105) = (KFPAN)
  RCONST(106) = (KAPNO)
  RCONST(107) = (3.00D-12)
  RCONST(108) = (J(22))
  RCONST(109) = (KFPAN*0.061)
  RCONST(110) = (KRO2HO2*0.706)
  RCONST(111) = (2.00D-12*RO2*0.7)
  RCONST(112) = (2.00D-12*RO2*0.3)
  RCONST(113) = (KRO2NO*0.3)
  RCONST(114) = (KRO2NO*0.7)
  RCONST(115) = (KBPAN)
  RCONST(116) = (3.60D-12)
  RCONST(117) = (3.00D-11)
  RCONST(118) = (J(41))
  RCONST(119) = (6.19D-12)
  RCONST(120) = (J(41))
  RCONST(121) = (KBPAN)
  RCONST(122) = (1.12D-12)
  RCONST(123) = (KBPAN)
  RCONST(124) = (2.52D-11)
  RCONST(125) = (3.00D-11)
  RCONST(126) = (J(41))
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE model_Global

      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE model_Rates

