! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Function of Chemical Model File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : model_Function.f90
! Time                 : Sat Apr 22 13:43:50 2017
! Working directory    : /work/home/dp626/DSMACC-testing
! Equation file        : model.kpp
! Output root filename : model
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE model_Function

  USE model_Parameters
  IMPLICIT NONE

! A - Rate for each equation
  REAL(kind=dp) :: A(NREACT)
!$OMP THREADPRIVATE(  A )

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Fun - time derivatives of variables - Agregate form
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      Vdot      - Time derivative of variable species concentrations
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun ( V, F, RCT, Vdot )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! Vdot - Time derivative of variable species concentrations
  REAL(kind=dp) :: Vdot(NVAR)


! Computation of equation rates
  A(1) = RCT(1)*V(3)*V(4)
  A(2) = RCT(2)*V(4)*V(24)
  A(3) = RCT(3)*V(21)*V(28)
  A(4) = RCT(4)*V(21)*V(28)
  A(5) = RCT(5)*V(21)*V(26)
  A(6) = RCT(6)*V(21)*V(26)
  A(7) = RCT(7)*V(21)*V(25)
  A(8) = RCT(8)*V(21)*V(22)
  A(9) = RCT(9)*V(21)
  A(10) = RCT(10)*V(21)
  A(11) = RCT(11)*V(21)
  A(12) = RCT(12)*V(19)
  A(13) = RCT(13)*V(19)*V(24)
  A(14) = RCT(14)*V(19)*V(24)
  A(15) = RCT(15)*V(20)
  A(16) = RCT(16)*V(20)
  A(17) = RCT(17)*V(20)*V(22)
  A(18) = RCT(18)*V(20)*V(24)
  A(19) = RCT(19)*V(17)
  A(20) = RCT(20)*V(17)*V(24)
  A(21) = RCT(21)*V(16)
  A(22) = RCT(22)*V(7)
  A(23) = RCT(23)*V(11)*V(24)
  A(24) = RCT(24)*V(23)
  A(25) = RCT(25)*V(23)*V(27)
  A(26) = RCT(26)*V(23)*V(26)
  A(27) = RCT(27)*V(23)*V(25)
  A(28) = RCT(28)*V(23)*V(25)
  A(29) = RCT(29)*V(5)
  A(30) = RCT(30)*V(26)*V(27)
  A(31) = RCT(31)*V(25)*V(27)
  A(32) = RCT(32)*V(26)*V(26)
  A(33) = RCT(33)*V(22)*V(26)
  A(34) = RCT(34)*V(22)*V(25)
  A(35) = RCT(35)*V(22)*V(25)
  A(36) = RCT(36)*V(9)
  A(37) = RCT(37)*V(5)
  A(38) = RCT(38)*V(24)*V(27)
  A(39) = RCT(39)*V(8)*V(24)
  A(40) = RCT(40)*V(13)*V(24)
  A(41) = RCT(41)*V(10)*V(24)
  A(42) = RCT(42)*V(27)*V(28)
  A(43) = RCT(43)*V(24)*V(28)
  A(44) = RCT(44)*V(28)*V(28)
  A(45) = RCT(45)*V(24)*V(26)
  A(46) = RCT(46)*V(24)*V(25)
  A(47) = 2e-11*V(22)*V(24)
  A(48) = RCT(48)*V(26)*V(28)
  A(49) = RCT(49)*V(25)*V(28)
  A(50) = RCT(50)*V(15)
  A(51) = RCT(51)*V(15)*V(24)
  A(52) = 4e-12*V(22)*V(28)
  A(53) = RCT(53)*V(12)*V(24)
  A(54) = RCT(54)*V(18)*V(24)
  A(55) = RCT(55)*V(14)*V(23)
  A(56) = RCT(56)*V(14)*V(24)
  A(57) = RCT(57)*V(6)
  A(58) = RCT(58)*V(27)
  A(59) = RCT(59)*V(27)
  A(60) = RCT(60)*V(10)
  A(61) = RCT(61)*V(25)
  A(62) = RCT(62)*V(22)
  A(63) = RCT(63)*V(22)
  A(64) = RCT(64)*V(12)
  A(65) = RCT(65)*V(18)
  A(66) = V(1)

! Aggregate function
  Vdot(1) = A(25)+A(43)-0.5*A(66)
  Vdot(2) = A(55)+A(57)
  Vdot(3) = -A(1)
  Vdot(4) = -A(1)-A(2)
  Vdot(5) = -A(29)-A(37)+A(58)
  Vdot(6) = A(56)-A(57)
  Vdot(7) = A(7)-A(22)
  Vdot(8) = A(16)-A(39)
  Vdot(9) = A(35)-A(36)
  Vdot(10) = -A(41)+A(44)-A(60)
  Vdot(11) = A(10)-A(23)
  Vdot(12) = A(45)-A(53)-A(64)
  Vdot(13) = A(15)+A(16)+A(17)+A(18)-A(40)
  Vdot(14) = -A(55)-A(56)
  Vdot(15) = A(49)-A(50)-A(51)
  Vdot(16) = A(6)+A(8)+A(9)+A(12)+A(19)-A(21)
  Vdot(17) = A(5)-A(19)-A(20)
  Vdot(18) = A(17)+A(46)-A(54)-A(65)
  Vdot(19) = A(3)-A(12)-A(13)-A(14)
  Vdot(20) = A(4)+A(11)+A(14)-A(15)-A(16)-A(17)-A(18)+A(20)+A(21)+A(23)
  Vdot(21) = A(1)+A(2)-A(3)-A(4)-A(5)-A(6)-A(7)-A(8)-A(9)-A(10)-A(11)+A(13)+A(22)
  Vdot(22) = -A(8)-A(17)+A(28)+A(31)-A(33)-A(34)-A(35)+A(36)-A(47)-A(52)+A(54)-A(62)-A(63)
  Vdot(23) = -A(24)-A(25)-A(26)-A(27)-A(28)+A(29)-A(55)+A(59)+A(61)+A(63)
  Vdot(24) = -A(2)+A(12)-A(13)-A(18)-A(20)-A(23)+2*A(37)-A(38)-A(39)-A(40)-A(41)+A(42)-A(43)-A(45)-A(46)-A(47)+A(48)&
               &-A(51)+A(52)-A(53)-A(54)-A(56)+2*A(60)+A(64)+A(65)
  Vdot(25) = A(6)-A(7)+A(8)+A(19)+A(20)+A(22)+A(26)-A(27)-A(28)+A(30)-A(31)+2*A(32)+2*A(33)-A(35)+A(36)-A(46)+A(47)&
               &+A(48)-A(49)+A(50)+A(51)+A(52)+A(53)-A(61)+A(63)+A(65)
  Vdot(26) = -A(5)-A(6)-A(26)+A(27)-A(30)-2*A(32)-A(33)+A(34)-A(45)-A(48)+A(61)+A(62)+A(64)
  Vdot(27) = A(24)-A(25)-A(30)-A(31)-A(38)-A(42)-A(58)-A(59)
  Vdot(28) = -A(3)-A(4)+2*A(15)+A(17)+A(18)+A(21)+A(23)+A(38)+A(39)+A(40)+A(41)-A(42)-A(43)-2*A(44)+A(47)-A(48)-A(49)&
               &+A(50)-A(52)+A(57)
      
END SUBROUTINE Fun

! End of Fun function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE model_Function

