! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Function of Chemical Model File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : model_Function.f90
! Time                 : Thu Feb 16 17:13:45 2017
! Working directory    : /work/home/dp626/DSMACC-testing
! Equation file        : model.kpp
! Output root filename : model
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE model_Function

  USE model_Parameters
  IMPLICIT NONE

! A - Rate for each equation
  REAL(kind=dp) :: A(NREACT)
!$OMP THREADPRIVATE(  A )

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Fun - time derivatives of variables - Agregate form
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      Vdot      - Time derivative of variable species concentrations
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun ( V, F, RCT, Vdot )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! Vdot - Time derivative of variable species concentrations
  REAL(kind=dp) :: Vdot(NVAR)


! Computation of equation rates
  A(1) = RCT(1)*V(41)
  A(2) = RCT(2)*V(41)*V(45)
  A(3) = RCT(3)*V(41)*V(47)
  A(4) = RCT(4)*V(41)*V(42)
  A(5) = RCT(5)*V(41)*V(42)
  A(6) = RCT(6)*V(4)
  A(7) = RCT(7)*V(45)*V(47)
  A(8) = RCT(8)*V(42)*V(45)
  A(9) = RCT(9)*V(47)*V(47)
  A(10) = RCT(10)*V(46)*V(47)
  A(11) = RCT(11)*V(42)*V(46)
  A(12) = RCT(12)*V(42)*V(46)
  A(13) = RCT(13)*V(6)
  A(14) = RCT(14)*V(4)
  A(15) = RCT(15)*V(43)*V(45)
  A(16) = RCT(16)*V(7)*V(43)
  A(17) = RCT(17)*V(30)*V(43)
  A(18) = RCT(18)*V(16)*V(43)
  A(19) = RCT(19)*V(44)*V(45)
  A(20) = RCT(20)*V(43)*V(44)
  A(21) = RCT(21)*V(44)*V(44)
  A(22) = RCT(22)*V(43)*V(47)
  A(23) = RCT(23)*V(42)*V(43)
  A(24) = 2e-11*V(43)*V(46)
  A(25) = RCT(25)*V(44)*V(47)
  A(26) = RCT(26)*V(42)*V(44)
  A(27) = RCT(27)*V(13)
  A(28) = RCT(28)*V(13)*V(43)
  A(29) = 4e-12*V(44)*V(46)
  A(30) = RCT(30)*V(11)*V(43)
  A(31) = RCT(31)*V(9)*V(43)
  A(32) = RCT(32)*V(12)*V(41)
  A(33) = RCT(33)*V(12)*V(43)
  A(34) = RCT(34)*V(5)
  A(35) = RCT(35)*V(45)
  A(36) = RCT(36)*V(45)
  A(37) = RCT(37)*V(16)
  A(38) = RCT(38)*V(42)
  A(39) = RCT(39)*V(46)
  A(40) = RCT(40)*V(46)
  A(41) = RCT(41)*V(11)
  A(42) = RCT(42)*V(9)
  A(43) = RCT(43)*V(3)
  A(44) = V(1)
  A(46) = RCT(46)*V(8)*V(43)
  A(47) = RCT(47)*V(31)
  A(48) = RCT(48)*V(31)*V(43)
  A(49) = RCT(49)*V(31)
  A(50) = RCT(50)*V(18)*V(43)
  A(51) = RCT(51)*V(18)*V(45)
  A(52) = RCT(52)*V(18)*V(45)
  A(53) = RCT(53)*V(10)*V(43)
  A(54) = RCT(54)*V(38)
  A(55) = RCT(55)*V(38)*V(42)
  A(56) = RCT(56)*V(38)*V(44)
  A(57) = RCT(57)*V(38)*V(47)
  A(58) = RCT(58)*V(28)
  A(59) = RCT(59)*V(28)*V(47)
  A(60) = RCT(60)*V(28)
  A(61) = RCT(61)*V(28)
  A(62) = RCT(62)*V(28)*V(44)
  A(63) = RCT(63)*V(28)*V(47)
  A(64) = RCT(64)*V(33)*V(47)
  A(65) = RCT(65)*V(33)*V(44)
  A(66) = RCT(66)*V(33)
  A(67) = RCT(67)*V(33)*V(47)
  A(68) = RCT(68)*V(33)
  A(69) = RCT(69)*V(33)*V(47)
  A(70) = RCT(70)*V(40)*V(43)
  A(71) = RCT(71)*V(40)*V(45)
  A(72) = RCT(72)*V(40)
  A(73) = RCT(73)*V(40)*V(45)
  A(74) = RCT(74)*V(36)*V(43)
  A(75) = RCT(75)*V(36)
  A(76) = RCT(76)*V(26)
  A(77) = RCT(77)*V(26)*V(43)
  A(78) = RCT(78)*V(15)
  A(79) = RCT(79)*V(15)*V(43)
  A(80) = RCT(80)*V(21)*V(43)
  A(81) = RCT(81)*V(21)
  A(82) = RCT(82)*V(22)*V(43)
  A(83) = RCT(83)*V(22)*V(43)
  A(84) = RCT(84)*V(22)
  A(85) = RCT(85)*V(34)*V(43)
  A(86) = RCT(86)*V(34)
  A(87) = RCT(87)*V(14)*V(43)
  A(88) = RCT(88)*V(27)*V(43)
  A(89) = RCT(89)*V(27)
  A(90) = RCT(90)*V(27)
  A(91) = RCT(91)*V(35)*V(43)
  A(92) = RCT(92)*V(35)*V(45)
  A(93) = RCT(93)*V(35)*V(45)
  A(94) = RCT(94)*V(35)
  A(95) = RCT(95)*V(37)*V(42)
  A(96) = RCT(96)*V(37)
  A(97) = RCT(97)*V(37)*V(44)
  A(98) = RCT(98)*V(37)
  A(99) = RCT(99)*V(37)
  A(100) = RCT(100)*V(37)*V(47)
  A(101) = RCT(101)*V(37)*V(47)
  A(102) = RCT(102)*V(37)*V(47)
  A(103) = RCT(103)*V(32)*V(44)
  A(104) = RCT(104)*V(32)
  A(105) = RCT(105)*V(32)*V(42)
  A(106) = RCT(106)*V(32)*V(47)
  A(107) = RCT(107)*V(29)*V(43)
  A(108) = RCT(108)*V(29)
  A(109) = RCT(109)*V(39)*V(42)
  A(110) = RCT(110)*V(39)*V(44)
  A(111) = RCT(111)*V(39)
  A(112) = RCT(112)*V(39)
  A(113) = RCT(113)*V(39)*V(47)
  A(114) = RCT(114)*V(39)*V(47)
  A(115) = RCT(115)*V(24)
  A(116) = RCT(116)*V(24)*V(43)
  A(117) = RCT(117)*V(17)*V(43)
  A(118) = RCT(118)*V(17)
  A(119) = RCT(119)*V(20)*V(43)
  A(120) = RCT(120)*V(20)
  A(121) = RCT(121)*V(25)
  A(122) = RCT(122)*V(25)*V(43)
  A(123) = RCT(123)*V(19)
  A(124) = RCT(124)*V(19)*V(43)
  A(125) = RCT(125)*V(23)*V(43)
  A(126) = RCT(126)*V(23)

! Aggregate function
  Vdot(1) = A(2)+A(20)-0.5*A(44)
  Vdot(2) = A(43)
  Vdot(3) = A(32)+A(34)-A(43)
  Vdot(4) = -A(6)-A(14)+A(35)
  Vdot(5) = A(33)-A(34)
  Vdot(6) = A(12)-A(13)
  Vdot(7) = -A(16)+A(47)
  Vdot(8) = -A(46)+A(58)
  Vdot(9) = A(23)-A(31)-A(42)
  Vdot(10) = A(52)-A(53)
  Vdot(11) = A(22)-A(30)-A(41)
  Vdot(12) = -A(32)-A(33)
  Vdot(13) = A(26)-A(27)-A(28)
  Vdot(14) = A(64)-A(87)
  Vdot(15) = A(56)-A(78)-A(79)
  Vdot(16) = -A(18)+A(21)-A(37)+A(73)+A(93)
  Vdot(17) = A(97)-A(117)-A(118)
  Vdot(18) = -A(50)-A(51)-A(52)
  Vdot(19) = A(109)-A(123)-A(124)
  Vdot(20) = A(103)-A(119)-A(120)
  Vdot(21) = A(59)-A(80)-A(81)
  Vdot(22) = A(62)-A(82)-A(83)-A(84)
  Vdot(23) = A(110)-A(125)-A(126)
  Vdot(24) = A(95)-A(115)-A(116)
  Vdot(25) = A(105)-A(121)-A(122)
  Vdot(26) = A(55)-A(76)-A(77)
  Vdot(27) = A(65)-A(88)-A(89)-A(90)
  Vdot(28) = A(54)+A(57)-A(58)-A(59)-A(60)-A(61)-A(62)-A(63)+A(78)+A(82)
  Vdot(29) = A(99)+A(101)-A(107)-A(108)+A(112)+A(113)+A(116)
  Vdot(30) = -A(17)+A(47)+A(48)+A(49)+A(51)+A(71)+A(75)+A(77)+A(85)+A(86)+A(92)+A(94)+A(113)+A(116)+A(122)
  Vdot(31) = A(46)-A(47)-A(48)-A(49)+A(60)+A(61)+A(63)+A(68)+A(69)+A(71)+A(72)+A(73)+A(75)+A(77)+A(80)+A(81)+A(83)+A(84)&
               &+A(90)+A(98)+A(99)+A(101)+A(102)+A(104)+A(106)+A(108)+A(120)+A(122)
  Vdot(32) = A(74)-A(103)-A(104)-A(105)-A(106)+A(119)+A(121)
  Vdot(33) = A(50)-A(64)-A(65)-A(66)-A(67)-A(68)-A(69)
  Vdot(34) = A(73)-A(85)-A(86)+A(93)+A(98)+A(102)+A(107)+A(126)
  Vdot(35) = A(66)+A(67)+A(87)+A(88)+A(89)-A(91)-A(92)-A(93)-A(94)
  Vdot(36) = -A(74)-A(75)+A(92)+A(93)+A(94)+A(96)+A(100)+A(111)+A(112)+A(114)+A(118)+A(126)
  Vdot(37) = A(70)-A(95)-A(96)-A(97)-A(98)-A(99)-A(100)-A(101)-A(102)+A(115)+A(117)
  Vdot(38) = -A(54)-A(55)-A(56)-A(57)+A(71)+A(72)+A(76)+A(79)+A(85)+A(86)+A(92)+A(94)+A(96)+A(100)+A(108)+A(111)+A(114)&
               &+A(118)
  Vdot(39) = A(91)-A(109)-A(110)-A(111)-A(112)-A(113)-A(114)+A(123)+A(125)
  Vdot(40) = A(51)+A(52)+A(68)+A(69)-A(70)-A(71)-A(72)-A(73)+A(90)+A(124)
  Vdot(41) = -A(1)-A(2)-A(3)-A(4)-A(5)+A(6)-A(32)+A(36)+A(38)+A(40)
  Vdot(42) = A(3)-A(4)-A(5)+A(7)-A(8)+2*A(9)+2*A(10)-A(12)+A(13)-A(23)+A(24)+A(25)-A(26)+A(27)+A(28)+A(29)+A(30)-A(38)&
               &+A(40)+A(42)-A(55)+A(57)+A(63)+A(67)+A(69)+A(76)+A(77)+A(80)+A(81)+A(87)-A(95)+A(100)+A(101)+A(102)-A(105)&
               &+A(106)-A(109)+A(113)+A(114)+A(115)+A(116)+A(121)+A(122)+A(123)+A(124)
  Vdot(43) = 2*A(14)-A(15)-A(16)-A(17)-A(18)+A(19)-A(20)-A(22)-A(23)-A(24)+A(25)-A(28)+A(29)-A(30)-A(31)-A(33)+2*A(37)&
               &+A(41)+A(42)-A(46)-A(48)-A(50)+A(51)-A(53)-A(70)+A(71)-A(74)-A(77)+A(78)-A(79)-A(80)-A(82)+A(84)-A(85)-A(87)&
               &+A(89)+A(90)-A(91)+A(92)-A(107)-A(116)-A(117)+A(118)-A(119)+A(120)-A(122)-A(124)-A(125)+A(126)
  Vdot(44) = A(15)+A(16)+A(17)+A(18)-A(19)-A(20)-2*A(21)+A(24)-A(25)-A(26)+A(27)-A(29)+A(34)+A(46)+A(48)+2*A(49)+A(51)&
               &+A(53)-A(56)+A(61)-A(62)+A(63)-A(65)+A(66)+A(67)+A(68)+A(69)+A(72)+2*A(75)+A(81)+A(84)+A(86)+A(89)+A(90)&
               &+A(94)-A(97)+A(98)+A(99)+A(101)+A(102)-A(103)+A(104)+A(106)+A(107)+A(108)-A(110)+A(112)+A(113)+A(120)+A(126)
  Vdot(45) = A(1)-A(2)-A(7)-A(8)-A(15)-A(19)-A(35)-A(36)-A(51)-A(52)-A(71)-A(73)-A(92)-A(93)
  Vdot(46) = A(5)+A(8)-A(10)-A(11)-A(12)+A(13)-A(24)-A(29)+A(31)-A(39)-A(40)
  Vdot(47) = -A(3)+A(4)-A(7)-2*A(9)-A(10)+A(11)-A(22)-A(25)+A(38)+A(39)+A(41)-A(57)-A(59)-A(63)-A(64)-A(67)-A(69)-A(100)&
               &-A(101)-A(102)-A(106)-A(113)-A(114)
      
END SUBROUTINE Fun

! End of Fun function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE model_Function

