! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : model_Rates.f90
! Time                 : Tue Mar  7 11:01:57 2017
! Working directory    : /work/home/dp626/DSMACC-testing
! Equation file        : model.kpp
! Output root filename : model
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE model_Rates

  USE model_Parameters
  USE model_Global
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR        

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0           
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )              
   END FUNCTION ARR2          

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(kind=dp) K0,K2,K3            
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2) 
      REAL A1, C1, A2, C2
      REAL(kind=dp) K1, K2      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3 

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1     
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL, INTENT(IN) :: n         ! exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL, INTENT(IN) :: m         ! exponent for high pressure limit
    REAL, INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions


! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE model_Parameters
      !USE model_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST

 
 USE constants
 !end of USE statements 
 !
 ! start of executable statements
 RO2 = & 
 C(ind_HEPTO2) + C(ind_HO3C76O2) + C(ind_C2H5CO3) + C(ind_NC4H9O2) + & 
   C(ind_CO3C75O2) + C(ind_C2H5O2) + C(ind_HO3C5O2) + C(ind_CH3CO3) + &  
   C(ind_HO1C4O2) + C(ind_C3H7CO3) + C(ind_BUTALO2) + C(ind_NC3H7O2) + &  
   C(ind_NBUTOLAO2) + C(ind_NBUTOLBO2) + C(ind_C71O2) + C(ind_HO2C4O2) + &  
   C(ind_C72O2) + C(ind_CH3O2) + C(ind_MEKAO2) + C(ind_DIEKBO2) + &  
   C(ind_CO25C73O2) + C(ind_CO25C74O2) + C(ind_HOCH2CH2O2) + &  
   C(ind_HCOCH2O2) + C(ind_ETHENO3O2) + C(ind_HO13C5O2) + C(ind_HO3C4O2) &  
   + C(ind_HO3C4CO3) + C(ind_HO1C3O2) + C(ind_HOC3H6CO3) + C(ind_IC3H7O2) &  
   + C(ind_CO2C3CO3) + C(ind_CH3COCH2O2) + C(ind_IPROPOLO2) + &  
   C(ind_HO2C3CO3) + C(ind_HYPROPO2) + C(ind_HO13C4O2) + C(ind_CO3C4CO3) &  
   + C(ind_MEKCO2) + C(ind_HO1CO3C4O2) + C(ind_HOCO3C54O2) + C(ind_C73O2) &  
   + C(ind_C74O2) + C(ind_HOCH2CO3) + C(ind_HCOCO3) + C(ind_NO3CH2CO3) + &  
   C(ind_HO3C3CO3) + C(ind_HOC2H4CO3) + C(ind_CH3CHOHCO3) + &  
   C(ind_HO13C3CO3) + C(ind_CO23C4CO3) + C(ind_BIACETO2) + &  
   C(ind_HCOCH2CO3 ) 
 CALL mcm_constants(time, temp, M, N2, O2, RO2, H2O) 
 
! End INLINED RCONST

  RCONST(1) = (3.90D-10)
  RCONST(2) = (1.59D-17*TEMP**2*EXP(478/TEMP))
  RCONST(3) = (KRO2HO2*0.820)
  RCONST(4) = (KRO2NO*0.278)
  RCONST(5) = (KRO2NO*0.722)
  RCONST(6) = (KRO2NO3)
  RCONST(7) = (2.50D-13*0.2*RO2)
  RCONST(8) = (2.50D-13*0.6*RO2)
  RCONST(9) = (2.50D-13*0.2*RO2)
  RCONST(10) = (J(41))
  RCONST(11) = (3.37D-11)
  RCONST(12) = (J(54))
  RCONST(13) = (3.69D-12)
  RCONST(14) = (2.58D+11*EXP(-3430/TEMP))
  RCONST(15) = (J(22))
  RCONST(16) = (7.89D-12)
  RCONST(17) = (1.59D-11)
  RCONST(18) = (KRO2HO2*0.820)
  RCONST(19) = (KRO2NO*0.111)
  RCONST(20) = (KRO2NO*0.889)
  RCONST(21) = (KRO2NO3)
  RCONST(22) = (2.50D-13*0.2*RO2)
  RCONST(23) = (2.50D-13*0.6*RO2)
  RCONST(24) = (2.50D-13*0.2*RO2)
  RCONST(25) = (KAPHO2*0.44)
  RCONST(26) = (KAPHO2*0.41)
  RCONST(27) = (KAPHO2*0.15)
  RCONST(28) = (6.7D-12*EXP(340/TEMP))
  RCONST(29) = (KFPAN)
  RCONST(30) = (KRO2NO3*1.74)
  RCONST(31) = (1.00D-11*0.7*RO2)
  RCONST(32) = (1.00D-11*0.3*RO2)
  RCONST(33) = (KRO2HO2*0.625)
  RCONST(34) = (KRO2NO*0.033)
  RCONST(35) = (KRO2NO*0.967)
  RCONST(36) = (KRO2NO3)
  RCONST(37) = (1.30D-12*0.2*RO2)
  RCONST(38) = (1.30D-12*0.2*RO2)
  RCONST(39) = (1.30D-12*0.6*RO2)
  RCONST(40) = (KRO2HO2*0.820)
  RCONST(41) = (KRO2NO)
  RCONST(42) = (KRO2NO3)
  RCONST(43) = (2.50D-13*RO2)
  RCONST(44) = (J(41))
  RCONST(45) = (3.84D-11)
  RCONST(46) = (J(54))
  RCONST(47) = (1.23D-11)
  RCONST(48) = (5.55D+11*EXP(-2945/TEMP))
  RCONST(49) = (2.32D-11)
  RCONST(50) = (J(22))
  RCONST(51) = (1.72D-11)
  RCONST(52) = (4.3D-13*EXP(870/TEMP))
  RCONST(53) = (2.55D-12*EXP(380/TEMP)*0.009)
  RCONST(54) = (2.55D-12*EXP(380/TEMP)*0.991)
  RCONST(55) = (KRO2NO3)
  RCONST(56) = (2*(KCH3O2*6.4D-14*(TEMP/300)**0*EXP(0/TEMP))**0.5*RO2*0.6)
  RCONST(57) = (2*(KCH3O2*6.4D-14*(TEMP/300)**0*EXP(0/TEMP))**0.5*RO2*0.2)
  RCONST(58) = (2*(KCH3O2*6.4D-14*(TEMP/300)**0*EXP(0/TEMP))**0.5*RO2*0.2)
  RCONST(59) = (4.42D-12)
  RCONST(60) = (J(41))
  RCONST(61) = (1.2D-12)
  RCONST(62) = (1.27D-12)
  RCONST(63) = (KBPPN)
  RCONST(64) = (J(41))
  RCONST(65) = (1.24D-11)
  RCONST(66) = (1.90D-12*EXP(190/TEMP))
  RCONST(67) = (J(53))
  RCONST(68) = (1.6D-12)
  RCONST(69) = (8.9D-14*EXP(-550/TEMP)*O2)
  RCONST(70) = (4.6D10*EXP(-3570/TEMP))
  RCONST(71) = (1.7D-12*EXP(-1500/TEMP))
  RCONST(72) = (6.0D-12*EXP(410/TEMP)*0.151)
  RCONST(73) = (6.0D-12*EXP(410/TEMP)*0.849)
  RCONST(74) = (J(16))
  RCONST(75) = (J(15))
  RCONST(76) = (5.3D-12*EXP(140/TEMP)*0.358)
  RCONST(77) = (5.3D-12*EXP(140/TEMP)*0.321)
  RCONST(78) = (5.3D-12*EXP(140/TEMP)*0.321)
  RCONST(79) = (J(41)+J(22))
  RCONST(80) = (1.42D-10)
  RCONST(81) = (1.45D+11*EXP(-3430/TEMP))
  RCONST(82) = (J(22))
  RCONST(83) = (1.52D-11*0.349)
  RCONST(84) = (1.52D-11*0.651)
  RCONST(85) = (KRO2HO2*0.706)
  RCONST(86) = (KRO2NO*0.052)
  RCONST(87) = (KRO2NO*0.948)
  RCONST(88) = (KRO2NO3)
  RCONST(89) = (1.30D-12*0.2*RO2)
  RCONST(90) = (1.30D-12*0.2*RO2)
  RCONST(91) = (1.30D-12*0.6*RO2)
  RCONST(92) = (KAPHO2*0.15)
  RCONST(93) = (KAPHO2*0.41)
  RCONST(94) = (KAPHO2*0.44)
  RCONST(95) = (7.5D-12*EXP(290/TEMP))
  RCONST(96) = (KFPAN)
  RCONST(97) = (4.0D-12)
  RCONST(98) = (2*(K298CH3O2*2.9D-12*EXP(500/TEMP))**0.5*RO2*0.3)
  RCONST(99) = (2*(K298CH3O2*2.9D-12*EXP(500/TEMP))**0.5*RO2*0.7)
  RCONST(100) = (J(22))
  RCONST(101) = (J(22))
  RCONST(102) = (6.60D-12*0.500)
  RCONST(103) = (6.60D-12*0.500)
  RCONST(104) = (J(41))
  RCONST(105) = (1.90D-12*EXP(190/TEMP))
  RCONST(106) = (8.01D-12)
  RCONST(107) = (J(52))
  RCONST(108) = (6.7D-13*EXP(-395/TEMP))
  RCONST(109) = (2.4D-14*EXP(-325/TEMP)*O2)
  RCONST(110) = (3.0D-12*EXP(20/TEMP)*0.05)
  RCONST(111) = (3.0D-12*EXP(20/TEMP)*0.9)
  RCONST(112) = (3.0D-12*EXP(20/TEMP)*0.05)
  RCONST(113) = (J(13))
  RCONST(114) = (1.4D-12*EXP(-1860/TEMP))
  RCONST(115) = (4.7D-12*EXP(345/TEMP)*0.95)
  RCONST(116) = (4.7D-12*EXP(345/TEMP)*0.05)
  RCONST(117) = (KRO2HO2*0.625)
  RCONST(118) = (KRO2NO*0.013)
  RCONST(119) = (KRO2NO*0.987)
  RCONST(120) = (KRO2NO3)
  RCONST(121) = (1.30D-12*0.6*RO2)
  RCONST(122) = (1.30D-12*0.2*RO2)
  RCONST(123) = (1.30D-12*0.2*RO2)
  RCONST(124) = (KAPHO2*0.15)
  RCONST(125) = (KAPHO2*0.44)
  RCONST(126) = (KAPHO2*0.41)
  RCONST(127) = (KAPNO)
  RCONST(128) = (KFPAN)
  RCONST(129) = (KRO2NO3*1.74)
  RCONST(130) = (1.00D-11*0.3*RO2)
  RCONST(131) = (1.00D-11*0.7*RO2)
  RCONST(132) = (KRO2HO2*0.625)
  RCONST(133) = (KRO2NO*0.083)
  RCONST(134) = (KRO2NO*0.917)
  RCONST(135) = (KRO2NO3)
  RCONST(136) = (2.50D-13*0.6*RO2)
  RCONST(137) = (2.50D-13*0.2*RO2)
  RCONST(138) = (2.50D-13*0.2*RO2)
  RCONST(139) = (3.3D-12*EXP(-2880/TEMP))
  RCONST(140) = (9.1D-15*EXP(-2580/TEMP))
  RCONST(141) = (KMT15)
  RCONST(142) = (KRO2HO2*0.520)
  RCONST(143) = (2.9D-12*EXP(350/TEMP)*0.020)
  RCONST(144) = (2.9D-12*EXP(350/TEMP)*0.980)
  RCONST(145) = (KRO2NO3)
  RCONST(146) = (2*(K298CH3O2*3D-13)**0.5*RO2*0.2)
  RCONST(147) = (2*(K298CH3O2*3D-13)**0.5*RO2*0.6)
  RCONST(148) = (2*(K298CH3O2*3D-13)**0.5*RO2*0.2)
  RCONST(149) = (KRO2HO2*0.625)
  RCONST(150) = (KRO2NO*0.042)
  RCONST(151) = (KRO2NO*0.958)
  RCONST(152) = (KRO2NO3)
  RCONST(153) = (8.80D-13*0.2*RO2)
  RCONST(154) = (8.80D-13*0.6*RO2)
  RCONST(155) = (8.80D-13*0.2*RO2)
  RCONST(156) = (KRO2HO2*0.625)
  RCONST(157) = (KRO2NO*0.083)
  RCONST(158) = (KRO2NO*0.917)
  RCONST(159) = (KRO2NO3)
  RCONST(160) = (8.80D-13*0.2*RO2)
  RCONST(161) = (8.80D-13*0.2*RO2)
  RCONST(162) = (8.80D-13*0.6*RO2)
  RCONST(163) = (KRO2HO2*0.820)
  RCONST(164) = (KRO2NO)
  RCONST(165) = (KRO2NO3)
  RCONST(166) = (8.80D-13*RO2)
  RCONST(167) = (KRO2HO2*0.625)
  RCONST(168) = (KRO2NO*0.033)
  RCONST(169) = (KRO2NO*0.967)
  RCONST(170) = (KRO2NO3)
  RCONST(171) = (1.30D-12*0.2*RO2)
  RCONST(172) = (1.30D-12*0.6*RO2)
  RCONST(173) = (1.30D-12*0.2*RO2)
  RCONST(174) = (KRO2HO2*0.820)
  RCONST(175) = (KRO2NO*0.139)
  RCONST(176) = (KRO2NO*0.861)
  RCONST(177) = (KRO2NO3)
  RCONST(178) = (8.80D-13*0.6*RO2)
  RCONST(179) = (8.80D-13*0.2*RO2)
  RCONST(180) = (8.80D-13*0.2*RO2)
  RCONST(181) = (J(41))
  RCONST(182) = (2.28D-11)
  RCONST(183) = (1.90D-12*EXP(190/TEMP))
  RCONST(184) = (J(53))
  RCONST(185) = (1.20D-11)
  RCONST(186) = (2.03D+11*EXP(-3430/TEMP))
  RCONST(187) = (1.61D-11)
  RCONST(188) = (J(15))
  RCONST(189) = (KNO3AL*5.5)
  RCONST(190) = (5.56D-11*0.611)
  RCONST(191) = (5.56D-11*0.389)
  RCONST(192) = (8.00D-13)
  RCONST(193) = (3.70D-12)
  RCONST(194) = (J(41))
  RCONST(195) = (3.8D-13*EXP(780/TEMP)*(1-1/(1+498*EXP(-1160/TEMP))))
  RCONST(196) = (3.8D-13*EXP(780/TEMP)*(1/(1+498*EXP(-1160/TEMP))))
  RCONST(197) = (2.3D-12*EXP(360/TEMP)*0.001)
  RCONST(198) = (2.3D-12*EXP(360/TEMP)*0.999)
  RCONST(199) = (KMT13)
  RCONST(200) = (1.2D-12)
  RCONST(201) = (2*KCH3O2*RO2*7.18*EXP(-885/TEMP))
  RCONST(202) = (2*KCH3O2*RO2*0.5*(1-7.18*EXP(-885/TEMP)))
  RCONST(203) = (2*KCH3O2*RO2*0.5*(1-7.18*EXP(-885/TEMP)))
  RCONST(204) = (3D-14)
  RCONST(205) = (KBPAN)
  RCONST(206) = (KRO2HO2*0.625)
  RCONST(207) = (KRO2NO*0.033)
  RCONST(208) = (KRO2NO*0.967)
  RCONST(209) = (KRO2NO3)
  RCONST(210) = (2.00D-12*0.2*RO2)
  RCONST(211) = (2.00D-12*0.6*RO2)
  RCONST(212) = (2.00D-12*0.2*RO2)
  RCONST(213) = (KRO2HO2*0.706)
  RCONST(214) = (KRO2NO*0.052)
  RCONST(215) = (KRO2NO*0.948)
  RCONST(216) = (KRO2NO3)
  RCONST(217) = (2.00D-12*0.2*RO2)
  RCONST(218) = (2.00D-12*0.6*RO2)
  RCONST(219) = (2.00D-12*0.2*RO2)
  RCONST(220) = (KRO2HO2*0.820)
  RCONST(221) = (KRO2NO)
  RCONST(222) = (KRO2NO3)
  RCONST(223) = (8.80D-13*0.2*RO2)
  RCONST(224) = (8.80D-13*0.6*RO2)
  RCONST(225) = (8.80D-13*0.2*RO2)
  RCONST(226) = (KRO2HO2*0.820)
  RCONST(227) = (KRO2NO)
  RCONST(228) = (KRO2NO3)
  RCONST(229) = (8.80D-13*0.2*RO2)
  RCONST(230) = (8.80D-13*0.6*RO2)
  RCONST(231) = (8.80D-13*0.2*RO2)
  RCONST(232) = (1.53D-13*EXP(1300/TEMP))
  RCONST(233) = (KRO2NO*0.005)
  RCONST(234) = (KRO2NO*0.995)
  RCONST(235) = (KRO2NO3)
  RCONST(236) = (2*(KCH3O2*7.8D-14*EXP(1000/TEMP))**0.5*RO2*0.2)
  RCONST(237) = (2*(KCH3O2*7.8D-14*EXP(1000/TEMP))**0.5*RO2*0.6)
  RCONST(238) = (2*(KCH3O2*7.8D-14*EXP(1000/TEMP))**0.5*RO2*0.2)
  RCONST(239) = (KRO2HO2*0.387)
  RCONST(240) = (KRO2NO)
  RCONST(241) = (KRO2NO3)
  RCONST(242) = (2.00D-12*0.2*RO2)
  RCONST(243) = (2.00D-12*0.6*RO2)
  RCONST(244) = (2.00D-12*0.2*RO2)
  RCONST(245) = (J(41))
  RCONST(246) = (1.90D-12*EXP(190/TEMP))
  RCONST(247) = (1.66D-11)
  RCONST(248) = (J(53))
  RCONST(249) = (5.85D-12)
  RCONST(250) = (8.74D+11*EXP(-3430/TEMP))
  RCONST(251) = (J(15))
  RCONST(252) = (KNO3AL*4.0)
  RCONST(253) = (2.64D-11)
  RCONST(254) = (1.11D-11)
  RCONST(255) = (1.8D-12)
  RCONST(256) = (8.29D-12)
  RCONST(257) = (J(41))
  RCONST(258) = (4.70D-12)
  RCONST(259) = (KBPAN)
  RCONST(260) = (1.90D-12*EXP(190/TEMP))
  RCONST(261) = (1.27D-10)
  RCONST(262) = (J(41))
  RCONST(263) = (J(15))
  RCONST(264) = (2.25D-11)
  RCONST(265) = (J(54)+J(15))
  RCONST(266) = (2.70D+14*EXP(-7398/TEMP))
  RCONST(267) = (KROSEC*O2)
  RCONST(268) = (KNO3AL*4.0)
  RCONST(269) = (7.15D-11)
  RCONST(270) = (J(15))
  RCONST(271) = (J(15))
  RCONST(272) = (KNO3AL*4.0)
  RCONST(273) = (4.88D-11*0.561)
  RCONST(274) = (4.88D-11*0.439)
  RCONST(275) = (KRO2HO2*0.387)
  RCONST(276) = (KRO2NO)
  RCONST(277) = (KRO2NO3)
  RCONST(278) = (6.00D-13*0.6*RO2)
  RCONST(279) = (6.00D-13*0.2*RO2)
  RCONST(280) = (6.00D-13*0.2*RO2)
  RCONST(281) = (J(11))
  RCONST(282) = (J(12))
  RCONST(283) = (5.5D-16)
  RCONST(284) = (5.4D-12*EXP(135/TEMP))
  RCONST(285) = (KDEC*0.37)
  RCONST(286) = (KDEC*0.50)
  RCONST(287) = (KDEC*0.13)
  RCONST(288) = (J(41))
  RCONST(289) = (1.10D-11)
  RCONST(290) = (1.90D-12*EXP(190/TEMP))
  RCONST(291) = (J(53))
  RCONST(292) = (5.8D-13)
  RCONST(293) = (2.6D-14*EXP(-255/TEMP)*O2)
  RCONST(294) = (3.24D-12*EXP(-1860/TEMP))
  RCONST(295) = (4.9D-12*EXP(405/TEMP))
  RCONST(296) = (J(14))
  RCONST(297) = (4.6D-12*EXP(70/TEMP)*0.494)
  RCONST(298) = (4.6D-12*EXP(70/TEMP)*0.063)
  RCONST(299) = (4.6D-12*EXP(70/TEMP)*0.443)
  RCONST(300) = (3.01D-11)
  RCONST(301) = (1.90D-12*EXP(190/TEMP))
  RCONST(302) = (J(41))
  RCONST(303) = (1.27D-12)
  RCONST(304) = (2.00D+14*EXP(-6354/TEMP))
  RCONST(305) = (3.44D-12)
  RCONST(306) = (J(22))
  RCONST(307) = (1.59D-11)
  RCONST(308) = (2.58D-11)
  RCONST(309) = (1.90D-12*EXP(190/TEMP))
  RCONST(310) = (J(41))
  RCONST(311) = (4.51D-12)
  RCONST(312) = (J(54))
  RCONST(313) = (2.70D+14*EXP(-7398/TEMP))
  RCONST(314) = (KROSEC*O2)
  RCONST(315) = (1.42D-11)
  RCONST(316) = (1.35D-11)
  RCONST(317) = (J(22))
  RCONST(318) = (J(41))
  RCONST(319) = (J(22))
  RCONST(320) = (5.12D-11)
  RCONST(321) = (KDEC)
  RCONST(322) = (J(41))
  RCONST(323) = (1.97D-11)
  RCONST(324) = (1.90D-12*EXP(190/TEMP))
  RCONST(325) = (J(53))
  RCONST(326) = (8.93D-12)
  RCONST(327) = (3.05D+11*EXP(-4240/TEMP))
  RCONST(328) = (KROPRIM*O2)
  RCONST(329) = (J(41)+J(22))
  RCONST(330) = (9.25D-11)
  RCONST(331) = (J(54)+J(22))
  RCONST(332) = (3.41D-12)
  RCONST(333) = (2.00D+14*EXP(-4714/TEMP))
  RCONST(334) = (J(22))
  RCONST(335) = (4.35D-11)
  RCONST(336) = (J(22)*2)
  RCONST(337) = (5.76D-12)
  RCONST(338) = (KRO2HO2*0.706)
  RCONST(339) = (KRO2NO*0.026)
  RCONST(340) = (KRO2NO*0.974)
  RCONST(341) = (KRO2NO3)
  RCONST(342) = (8.40D-13*0.2*RO2)
  RCONST(343) = (8.40D-13*0.6*RO2)
  RCONST(344) = (8.40D-13*0.2*RO2)
  RCONST(345) = (1.46D-11)
  RCONST(346) = (J(22))
  RCONST(347) = (KRO2HO2*0.625)
  RCONST(348) = (KRO2NO*0.017)
  RCONST(349) = (KRO2NO*0.983)
  RCONST(350) = (KRO2NO3)
  RCONST(351) = (2.00D-12*0.2*RO2)
  RCONST(352) = (2.00D-12*0.6*RO2)
  RCONST(353) = (2.00D-12*0.2*RO2)
  RCONST(354) = (KAPHO2*0.56)
  RCONST(355) = (KAPHO2*0.44)
  RCONST(356) = (KAPNO)
  RCONST(357) = (KFPAN)
  RCONST(358) = (KRO2NO3*1.74)
  RCONST(359) = (1.00D-11*RO2)
  RCONST(360) = (J(15))
  RCONST(361) = (KNO3AL*5.5)
  RCONST(362) = (6.76D-11)
  RCONST(363) = (J(41))
  RCONST(364) = (5.3D-12*EXP(190/TEMP)*0.6)
  RCONST(365) = (5.3D-12*EXP(190/TEMP)*0.4)
  RCONST(366) = (J(51))
  RCONST(367) = (4.0D-13*EXP(-845/TEMP))
  RCONST(368) = (7.2D-14*EXP(-1080/TEMP)*O2)
  RCONST(369) = (KMT14)
  RCONST(370) = (2.85D-12*EXP(-345/TEMP))
  RCONST(371) = (4.88D-11)
  RCONST(372) = (1.90D-12*EXP(190/TEMP))
  RCONST(373) = (J(41)+J(22))
  RCONST(374) = (9.64D-13)
  RCONST(375) = (J(53)+J(22))
  RCONST(376) = (KROPRIM*O2)
  RCONST(377) = (1.30D+11*EXP(-4127/TEMP))
  RCONST(378) = (5.36D-11)
  RCONST(379) = (1.90D-12*EXP(190/TEMP))
  RCONST(380) = (J(41)+J(22))
  RCONST(381) = (2.13D-12)
  RCONST(382) = (J(22)+J(53))
  RCONST(383) = (8.40D+10*EXP(-2567/TEMP))
  RCONST(384) = (J(22)*2)
  RCONST(385) = (J(41))
  RCONST(386) = (5.53D-11)
  RCONST(387) = (KDEC)
  RCONST(388) = (J(35))
  RCONST(389) = (1.86D-12)
  RCONST(390) = (J(22)*2)
  RCONST(391) = (2.41D-11)
  RCONST(392) = (J(22)*2)
  RCONST(393) = (J(41))
  RCONST(394) = (5.53D-11)
  RCONST(395) = (KDEC)
  RCONST(396) = (J(35))
  RCONST(397) = (1.86D-12)
  RCONST(398) = (J(22)*2)
  RCONST(399) = (2.41D-11)
  RCONST(400) = (1.90D-12*EXP(190/TEMP))
  RCONST(401) = (1.38D-11)
  RCONST(402) = (J(41))
  RCONST(403) = (8.40D-13)
  RCONST(404) = (9.50D+13*EXP(-5988/TEMP))
  RCONST(405) = (KROPRIM*O2)
  RCONST(406) = (1.45D-11)
  RCONST(407) = (KNO3AL)
  RCONST(408) = (1.00D-11*0.200)
  RCONST(409) = (1.00D-11*0.800)
  RCONST(410) = (J(15))
  RCONST(411) = (2.91D-11)
  RCONST(412) = (1.90D-12*EXP(190/TEMP))
  RCONST(413) = (J(41))
  RCONST(414) = (J(15))
  RCONST(415) = (KDEC)
  RCONST(416) = (J(31))
  RCONST(417) = (J(33))
  RCONST(418) = (J(32))
  RCONST(419) = (KNO3AL*0.6)
  RCONST(420) = (KNO3AL*0.4)
  RCONST(421) = (3.1D-12*EXP(340/TEMP)*0.6)
  RCONST(422) = (3.1D-12*EXP(340/TEMP)*0.4)
  RCONST(423) = (KRO2HO2*0.520)
  RCONST(424) = (KRO2NO*0.019)
  RCONST(425) = (KRO2NO*0.981)
  RCONST(426) = (KRO2NO3)
  RCONST(427) = (6.00D-13*0.6*RO2)
  RCONST(428) = (6.00D-13*0.2*RO2)
  RCONST(429) = (6.00D-13*0.2*RO2)
  RCONST(430) = (KAPHO2*0.44)
  RCONST(431) = (KAPHO2*0.15)
  RCONST(432) = (KAPHO2*0.41)
  RCONST(433) = (KAPNO*4.0)
  RCONST(434) = (KFPAN)
  RCONST(435) = (KRO2NO3*1.74)
  RCONST(436) = (1.00D-11*0.7*RO2)
  RCONST(437) = (1.00D-11*0.3*RO2)
  RCONST(438) = (KRO2HO2*0.520)
  RCONST(439) = (2.7D-12*EXP(360/TEMP)*0.042)
  RCONST(440) = (2.7D-12*EXP(360/TEMP)*0.958)
  RCONST(441) = (KRO2NO3)
  RCONST(442) = (2*(KCH3O2*1.6D-12*EXP(-2200/TEMP))**0.5*RO2*0.2)
  RCONST(443) = (2*(KCH3O2*1.6D-12*EXP(-2200/TEMP))**0.5*RO2*0.6)
  RCONST(444) = (2*(KCH3O2*1.6D-12*EXP(-2200/TEMP))**0.5*RO2*0.2)
  RCONST(445) = (KAPHO2*0.44)
  RCONST(446) = (KAPHO2*0.56)
  RCONST(447) = (KAPNO)
  RCONST(448) = (KFPAN)
  RCONST(449) = (KRO2NO3*1.74)
  RCONST(450) = (1.00D-11*RO2)
  RCONST(451) = (1.36D-13*EXP(1250/TEMP)*0.15)
  RCONST(452) = (1.36D-13*EXP(1250/TEMP)*0.85)
  RCONST(453) = (KRO2NO)
  RCONST(454) = (KRO2NO3)
  RCONST(455) = (2*(K298CH3O2*8.0D-12)**0.5*RO2*0.2)
  RCONST(456) = (2*(K298CH3O2*8.0D-12)**0.5*RO2*0.6)
  RCONST(457) = (2*(K298CH3O2*8.0D-12)**0.5*RO2*0.2)
  RCONST(458) = (KRO2HO2*0.520)
  RCONST(459) = (KRO2NO*0.991)
  RCONST(460) = (KRO2NO*0.009)
  RCONST(461) = (KRO2NO3)
  RCONST(462) = (2.00D-12*0.2*RO2)
  RCONST(463) = (2.00D-12*0.6*RO2)
  RCONST(464) = (2.00D-12*0.2*RO2)
  RCONST(465) = (KAPHO2*0.15)
  RCONST(466) = (KAPHO2*0.41)
  RCONST(467) = (KAPHO2*0.44)
  RCONST(468) = (KAPNO)
  RCONST(469) = (KFPAN)
  RCONST(470) = (KRO2NO3*1.74)
  RCONST(471) = (1.00D-11*0.3*RO2)
  RCONST(472) = (1.00D-11*0.7*RO2)
  RCONST(473) = (1.90D-12*EXP(190/TEMP))
  RCONST(474) = (1.62D-12)
  RCONST(475) = (J(41))
  RCONST(476) = (7.00D+03)
  RCONST(477) = (KROPRIM*O2)
  RCONST(478) = (KNO3AL)
  RCONST(479) = (3.40D-12)
  RCONST(480) = (J(57))
  RCONST(481) = (J(56))
  RCONST(482) = (1.20D-15)
  RCONST(483) = (1.00D-14)
  RCONST(484) = (1.00D-15)
  RCONST(485) = (7.00D-14)
  RCONST(486) = (6.00D-18*H2O)
  RCONST(487) = (1.00D-17*H2O)
  RCONST(488) = (KRO2HO2*0.520)
  RCONST(489) = (KRO2NO3)
  RCONST(490) = (8.80D-13*0.2*RO2)
  RCONST(491) = (8.80D-13*0.6*RO2)
  RCONST(492) = (8.80D-13*0.2*RO2)
  RCONST(493) = (KRO2NO*0.977)
  RCONST(494) = (KRO2NO*0.023)
  RCONST(495) = (J(34))
  RCONST(496) = (KNO3AL*4.0)
  RCONST(497) = (1.39D-11)
  RCONST(498) = (KRO2HO2*0.625)
  RCONST(499) = (KRO2NO*0.007)
  RCONST(500) = (KRO2NO*0.993)
  RCONST(501) = (KRO2NO3)
  RCONST(502) = (2.00D-12*0.2*RO2)
  RCONST(503) = (2.00D-12*0.6*RO2)
  RCONST(504) = (2.00D-12*0.2*RO2)
  RCONST(505) = (KAPHO2*0.15)
  RCONST(506) = (KAPHO2*0.41)
  RCONST(507) = (KAPHO2*0.44)
  RCONST(508) = (KAPNO)
  RCONST(509) = (KFPAN)
  RCONST(510) = (KRO2NO3*1.74)
  RCONST(511) = (1.00D-11*0.3*RO2)
  RCONST(512) = (1.00D-11*0.7*RO2)
  RCONST(513) = (J(41))
  RCONST(514) = (3.98D-11)
  RCONST(515) = (J(53))
  RCONST(516) = (7.51D-12)
  RCONST(517) = (2.00D+14*EXP(-4714/TEMP))
  RCONST(518) = (2.46D-11)
  RCONST(519) = (J(22))
  RCONST(520) = (1.51D-11)
  RCONST(521) = (2.14D-11)
  RCONST(522) = (1.90D-12*EXP(190/TEMP))
  RCONST(523) = (J(41))
  RCONST(524) = (3.03D-12)
  RCONST(525) = (2.00D+14*EXP(-5538/TEMP))
  RCONST(526) = (KNO3AL*4.0)
  RCONST(527) = (3.08D-11)
  RCONST(528) = (J(15))
  RCONST(529) = (J(41))
  RCONST(530) = (3.84D-11)
  RCONST(531) = (KBPAN)
  RCONST(532) = (1.20D-11)
  RCONST(533) = (KRO2HO2*0.625)
  RCONST(534) = (KRO2NO)
  RCONST(535) = (KRO2NO3)
  RCONST(536) = (2.00D-12*0.2*RO2)
  RCONST(537) = (2.00D-12*0.6*RO2)
  RCONST(538) = (2.00D-12*0.2*RO2)
  RCONST(539) = (KRO2HO2*0.625)
  RCONST(540) = (KRO2NO)
  RCONST(541) = (KRO2NO3)
  RCONST(542) = (2.00D-12*0.2*RO2)
  RCONST(543) = (2.00D-12*0.6*RO2)
  RCONST(544) = (2.00D-12*0.2*RO2)
  RCONST(545) = (KRO2HO2*0.706)
  RCONST(546) = (KRO2NO)
  RCONST(547) = (KRO2NO3)
  RCONST(548) = (8.80D-13*0.2*RO2)
  RCONST(549) = (8.80D-13*0.2*RO2)
  RCONST(550) = (8.80D-13*0.6*RO2)
  RCONST(551) = (KRO2HO2*0.820)
  RCONST(552) = (KRO2NO)
  RCONST(553) = (KRO2NO3)
  RCONST(554) = (8.80D-13*RO2)
  RCONST(555) = (KRO2HO2*0.820)
  RCONST(556) = (KRO2NO)
  RCONST(557) = (KRO2NO3)
  RCONST(558) = (8.80D-13*RO2)
  RCONST(559) = (KAPHO2*0.44)
  RCONST(560) = (KAPHO2*0.15)
  RCONST(561) = (KAPHO2*0.41)
  RCONST(562) = (KAPNO)
  RCONST(563) = (KFPAN)
  RCONST(564) = (KRO2NO3*1.74)
  RCONST(565) = (1.00D-11*0.7*RO2)
  RCONST(566) = (1.00D-11*0.3*RO2)
  RCONST(567) = (KAPHO2*0.15)
  RCONST(568) = (KAPHO2*0.41)
  RCONST(569) = (KAPHO2*0.44)
  RCONST(570) = (KAPNO)
  RCONST(571) = (KFPAN)
  RCONST(572) = (KRO2NO3*1.74)
  RCONST(573) = (1.00D-11*0.7*RO2)
  RCONST(574) = (1.00D-11*0.3*RO2)
  RCONST(575) = (J(41))
  RCONST(576) = (1.90D-12*EXP(190/TEMP))
  RCONST(577) = (1.52D-11)
  RCONST(578) = (J(53))
  RCONST(579) = (4.44D-12)
  RCONST(580) = (KROPRIM*O2)
  RCONST(581) = (J(15))
  RCONST(582) = (KNO3AL*2.4)
  RCONST(583) = (3.06D-11)
  RCONST(584) = (9.73D-12)
  RCONST(585) = (9.64D-12)
  RCONST(586) = (J(41))
  RCONST(587) = (1.31D-11)
  RCONST(588) = (KBPAN)
  RCONST(589) = (5.92D-12)
  RCONST(590) = (J(41))
  RCONST(591) = (1.66D-11)
  RCONST(592) = (1.90D-12*EXP(190/TEMP))
  RCONST(593) = (J(54))
  RCONST(594) = (6.2D-13*EXP(-230/TEMP))
  RCONST(595) = (1.5D-14*EXP(-230/TEMP)*O2)
  RCONST(596) = (8.8D-12*EXP(-1320/TEMP)+1.7D-14*EXP(423/TEMP))
  RCONST(597) = (J(21))
  RCONST(598) = (2.6D-12*EXP(200/TEMP)*0.861)
  RCONST(599) = (2.6D-12*EXP(200/TEMP)*0.139)
  RCONST(600) = (4.18D-12)
  RCONST(601) = (J(41)+J(22))
  RCONST(602) = (5.93D-13)
  RCONST(603) = (KBPAN)
  RCONST(604) = (KDEC)
  RCONST(605) = (1.90D-12*EXP(190/TEMP))
  RCONST(606) = (8.39D-12)
  RCONST(607) = (J(22))
  RCONST(608) = (J(41))
  RCONST(609) = (1.6D-12*EXP(305/TEMP))
  RCONST(610) = (J(22))
  RCONST(611) = (J(34))
  RCONST(612) = (KNO3AL*2.4)
  RCONST(613) = (1.9D-12*EXP(575/TEMP))
  RCONST(614) = (1.83D-11)
  RCONST(615) = (1.90D-12*EXP(190/TEMP))
  RCONST(616) = (J(41))
  RCONST(617) = (2.00D+14*EXP(-5505/TEMP))
  RCONST(618) = (1.71D-12)
  RCONST(619) = (KNO3AL*2.4)
  RCONST(620) = (1.7D-11)
  RCONST(621) = (J(17))
  RCONST(622) = (1.20D-11*0.613)
  RCONST(623) = (1.20D-11*0.387)
  RCONST(624) = (2.78D-11)
  RCONST(625) = (J(41))
  RCONST(626) = (3.12D-11)
  RCONST(627) = (KBPAN)
  RCONST(628) = (9.00D-12)
  RCONST(629) = (KAPHO2*0.44)
  RCONST(630) = (KAPHO2*0.15)
  RCONST(631) = (KAPHO2*0.41)
  RCONST(632) = (KAPNO)
  RCONST(633) = (KFPAN)
  RCONST(634) = (KRO2NO3*1.74)
  RCONST(635) = (1.00D-11*0.7*RO2)
  RCONST(636) = (1.00D-11*0.3*RO2)
  RCONST(637) = (4.5D-13)
  RCONST(638) = (2.44D-11)
  RCONST(639) = (1.90D-12*EXP(190/TEMP))
  RCONST(640) = (J(41))
  RCONST(641) = (2.00D+14*EXP(-6410/TEMP))
  RCONST(642) = (9.16D-13)
  RCONST(643) = (J(41))
  RCONST(644) = (2.56D-11)
  RCONST(645) = (1.90D-12*EXP(190/TEMP))
  RCONST(646) = (7.29D-12)
  RCONST(647) = (2.00D+14*EXP(-5538/TEMP))
  RCONST(648) = (J(15))
  RCONST(649) = (KNO3AL*4.0)
  RCONST(650) = (3.19D-11)
  RCONST(651) = (2.01D-11)
  RCONST(652) = (J(22))
  RCONST(653) = (1.90D-12)
  RCONST(654) = (J(41)+J(22))
  RCONST(655) = (5.36D-12)
  RCONST(656) = (KBPAN)
  RCONST(657) = (1.44D-12)
  RCONST(658) = (J(35))
  RCONST(659) = (1.39D-11)
  RCONST(660) = (KAPHO2*0.44)
  RCONST(661) = (KAPHO2*0.56)
  RCONST(662) = (KAPNO)
  RCONST(663) = (KFPAN)
  RCONST(664) = (KRO2NO3*1.74)
  RCONST(665) = (1.00D-11*RO2)
  RCONST(666) = (9.55D-12)
  RCONST(667) = (1.90D-12*EXP(190/TEMP))
  RCONST(668) = (J(22))
  RCONST(669) = (J(41))
  RCONST(670) = (KDEC)
  RCONST(671) = (1.90D-12*EXP(190/TEMP))
  RCONST(672) = (2.16D-11)
  RCONST(673) = (J(41)+J(22))
  RCONST(674) = (KDEC)
  RCONST(675) = (1.57D-11)
  RCONST(676) = (J(22))
  RCONST(677) = (KNO3AL*4.0)
  RCONST(678) = (2.56D-11)
  RCONST(679) = (J(34))
  RCONST(680) = (3.57D-11)
  RCONST(681) = (J(22))
  RCONST(682) = (J(41))
  RCONST(683) = (KDEC)
  RCONST(684) = (1.88D-11)
  RCONST(685) = (J(22))
  RCONST(686) = (J(41)+J(35))
  RCONST(687) = (J(22))
  RCONST(688) = (1.70D-11)
  RCONST(689) = (KDEC)
  RCONST(690) = (J(41))
  RCONST(691) = (J(35))
  RCONST(692) = (1.70D-11)
  RCONST(693) = (KDEC)
  RCONST(694) = (2.73D-12)
  RCONST(695) = (6.19D-12)
  RCONST(696) = (J(41))
  RCONST(697) = (1.12D-12)
  RCONST(698) = (KBPAN)
  RCONST(699) = (J(34))
  RCONST(700) = (1.23D-11)
  RCONST(701) = (J(41)+J(15))
  RCONST(702) = (1.58D-11)
  RCONST(703) = (KBPAN)
  RCONST(704) = (1.22D-11)
  RCONST(705) = (KAPHO2*0.15)
  RCONST(706) = (KAPHO2*0.41)
  RCONST(707) = (KAPHO2*0.44)
  RCONST(708) = (KAPNO)
  RCONST(709) = (KFPAN)
  RCONST(710) = (KRO2NO3*1.74)
  RCONST(711) = (1.00D-11*0.3*RO2)
  RCONST(712) = (1.00D-11*0.7*RO2)
  RCONST(713) = (KAPHO2*0.44)
  RCONST(714) = (KAPHO2*0.56)
  RCONST(715) = (KAPNO)
  RCONST(716) = (KFPAN)
  RCONST(717) = (KRO2NO3*1.74)
  RCONST(718) = (1.00D-11*RO2)
  RCONST(719) = (1.68D-13)
  RCONST(720) = (3.63D-12)
  RCONST(721) = (J(41))
  RCONST(722) = (1.12D-14)
  RCONST(723) = (KBPAN)
  RCONST(724) = (KAPHO2*0.56)
  RCONST(725) = (KAPHO2*0.44)
  RCONST(726) = (KAPNO)
  RCONST(727) = (KFPAN)
  RCONST(728) = (KRO2NO3*1.74)
  RCONST(729) = (1.00D-11*RO2)
  RCONST(730) = (J(15))
  RCONST(731) = (J(35))
  RCONST(732) = (KNO3AL*5.5)
  RCONST(733) = (6.65D-11)
  RCONST(734) = (1.38D-11)
  RCONST(735) = (J(41))
  RCONST(736) = (3.82D-12)
  RCONST(737) = (KBPAN)
  RCONST(738) = (KAPHO2*0.44)
  RCONST(739) = (KAPHO2*0.56)
  RCONST(740) = (KAPNO)
  RCONST(741) = (KFPAN)
  RCONST(742) = (KRO2NO3*1.74)
  RCONST(743) = (1.00D-11*RO2)
  RCONST(744) = (1.39D-11)
  RCONST(745) = (J(41))
  RCONST(746) = (1.73D-11)
  RCONST(747) = (KBPAN)
  RCONST(748) = (4.51D-12)
  RCONST(749) = (9.34D-12)
  RCONST(750) = (J(41))
  RCONST(751) = (2.34D-12)
  RCONST(752) = (KBPAN)
  RCONST(753) = (J(41))
  RCONST(754) = (1.86D-11)
  RCONST(755) = (KBPAN)
  RCONST(756) = (8.22D-12)
  RCONST(757) = (KRO2HO2*0.625)
  RCONST(758) = (KRO2NO)
  RCONST(759) = (KRO2NO3)
  RCONST(760) = (2.00D-12*0.6*RO2)
  RCONST(761) = (2.00D-12*0.2*RO2)
  RCONST(762) = (2.00D-12*0.2*RO2)
  RCONST(763) = (KAPHO2*0.15)
  RCONST(764) = (KAPHO2*0.41)
  RCONST(765) = (KAPHO2*0.44)
  RCONST(766) = (KAPNO)
  RCONST(767) = (KFPAN)
  RCONST(768) = (KRO2NO3*1.74)
  RCONST(769) = (1.00D-11*0.3*RO2)
  RCONST(770) = (1.00D-11*0.7*RO2)
  RCONST(771) = (J(41)+J(15))
  RCONST(772) = (4.23D-12)
  RCONST(773) = (KBPAN)
  RCONST(774) = (3.12D-13)
  RCONST(775) = (J(41)+J(35))
  RCONST(776) = (1.90D-12*EXP(190/TEMP))
  RCONST(777) = (5.99D-12)
  RCONST(778) = (KDEC)
  RCONST(779) = (J(35))
  RCONST(780) = (2.69D-12)
  RCONST(781) = (J(34))
  RCONST(782) = (J(35))
  RCONST(783) = (KNO3AL*4.0)
  RCONST(784) = (1.23D-11)
  RCONST(785) = (J(15))
  RCONST(786) = (2.14D-11)
  RCONST(787) = (J(41)+J(15))
  RCONST(788) = (2.49D-11)
  RCONST(789) = (KBPAN)
  RCONST(790) = (2.10D-11)
  RCONST(791) = (6.00E-34*O2*O2*((TEMP/300)**-2.6)+5.60E-34*O2*N2*((TEMP/300)**-2.6))
  RCONST(792) = (8.00E-12*EXP(-2060/TEMP))
  RCONST(793) = (KMT01)
  RCONST(794) = (5.50E-12*EXP(188/TEMP))
  RCONST(795) = (KMT02)
  RCONST(796) = (3.20E-11*O2*EXP(67/TEMP)+2.0E-11*N2*EXP(130/TEMP))
  RCONST(797) = (1.40E-12*EXP(-1310/TEMP))
  RCONST(798) = (1.40E-13*EXP(-2470/TEMP))
  RCONST(799) = (3.30E-39*EXP(530/TEMP)*O2)
  RCONST(800) = (1.80E-11*EXP(110/TEMP))
  RCONST(801) = (4.50E-14*EXP(-1260/TEMP))
  RCONST(802) = (KMT03)
  RCONST(803) = (KMT04)
  RCONST(804) = (2.14E-10*H2O)
  RCONST(805) = (1.70E-12*EXP(-940/TEMP))
  RCONST(806) = (7.70E-12*EXP(-2100/TEMP))
  RCONST(807) = (KMT05)
  RCONST(808) = (2.90E-12*EXP(-160/TEMP))
  RCONST(809) = (2.03E-16*((TEMP/300)**4.57)*EXP(693/TEMP))
  RCONST(810) = (4.80E-11*EXP(250/TEMP))
  RCONST(811) = (2.20E-13*KMT06*EXP(600/TEMP)+1.90E-33*M*KMT06*EXP(980/TEMP))
  RCONST(812) = (KMT07)
  RCONST(813) = (KMT08)
! RCONST(814) = constant rate coefficient
  RCONST(815) = (3.45E-12*EXP(270/TEMP))
  RCONST(816) = (KMT09)
  RCONST(817) = (KMT10)
  RCONST(818) = (3.20E-13*EXP(690/TEMP))
! RCONST(819) = constant rate coefficient
  RCONST(820) = (2.50E-12*EXP(260/TEMP))
  RCONST(821) = (KMT11)
  RCONST(822) = (4.00E-32*EXP(-1000/TEMP)*M)
  RCONST(823) = (KMT12)
  RCONST(824) = (1.30E-12*EXP(-330/TEMP)*O2)
  RCONST(825) = (J(1))
  RCONST(826) = (J(2))
  RCONST(827) = (J(3))
  RCONST(828) = (J(4))
  RCONST(829) = (J(5))
  RCONST(830) = (J(6))
  RCONST(831) = (J(7))
  RCONST(832) = (J(8))
! RCONST(833) = constant rate coefficient
! RCONST(834) = constant rate coefficient
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE model_Global

      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE model_Rates

