! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : model_Parameters.f90
! Time                 : Thu Feb 16 17:13:45 2017
! Working directory    : /work/home/dp626/DSMACC-testing
! Equation file        : model.kpp
! Output root filename : model
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE model_Parameters

  USE model_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 48 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 47 
! NFLUX - Number of Reaction Flux species
  INTEGER, PARAMETER :: NFLUX = 1 
! NFAM - Number of Prod/Loss Families
  INTEGER, PARAMETER :: NFAM = 1 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 46 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 1 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 126 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 48 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 349 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 383 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 48 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_DUMMY = 1 
  INTEGER, PARAMETER :: ind_SA = 2 
  INTEGER, PARAMETER :: ind_SO3 = 3 
  INTEGER, PARAMETER :: ind_O1D = 4 
  INTEGER, PARAMETER :: ind_HSO3 = 5 
  INTEGER, PARAMETER :: ind_N2O5 = 6 
  INTEGER, PARAMETER :: ind_H2 = 7 
  INTEGER, PARAMETER :: ind_CH3OH = 8 
  INTEGER, PARAMETER :: ind_HNO3 = 9 
  INTEGER, PARAMETER :: ind_HCOOH = 10 
  INTEGER, PARAMETER :: ind_HONO = 11 
  INTEGER, PARAMETER :: ind_SO2 = 12 
  INTEGER, PARAMETER :: ind_HO2NO2 = 13 
  INTEGER, PARAMETER :: ind_RU14NO3 = 14 
  INTEGER, PARAMETER :: ind_CH3CO3H = 15 
  INTEGER, PARAMETER :: ind_H2O2 = 16 
  INTEGER, PARAMETER :: ind_RU10OOH = 17 
  INTEGER, PARAMETER :: ind_C5H8 = 18 
  INTEGER, PARAMETER :: ind_RU12PAN = 19 
  INTEGER, PARAMETER :: ind_HOCH2CO3H = 20 
  INTEGER, PARAMETER :: ind_CH3NO3 = 21 
  INTEGER, PARAMETER :: ind_CH3OOH = 22 
  INTEGER, PARAMETER :: ind_RU12OOH = 23 
  INTEGER, PARAMETER :: ind_MPAN = 24 
  INTEGER, PARAMETER :: ind_PHAN = 25 
  INTEGER, PARAMETER :: ind_PAN = 26 
  INTEGER, PARAMETER :: ind_RU14OOH = 27 
  INTEGER, PARAMETER :: ind_CH3O2 = 28 
  INTEGER, PARAMETER :: ind_CARB7 = 29 
  INTEGER, PARAMETER :: ind_CO = 30 
  INTEGER, PARAMETER :: ind_HCHO = 31 
  INTEGER, PARAMETER :: ind_HOCH2CO3 = 32 
  INTEGER, PARAMETER :: ind_RU14O2 = 33 
  INTEGER, PARAMETER :: ind_CARB6 = 34 
  INTEGER, PARAMETER :: ind_UCARB12 = 35 
  INTEGER, PARAMETER :: ind_HOCH2CHO = 36 
  INTEGER, PARAMETER :: ind_RU10O2 = 37 
  INTEGER, PARAMETER :: ind_CH3CO3 = 38 
  INTEGER, PARAMETER :: ind_RU12O2 = 39 
  INTEGER, PARAMETER :: ind_UCARB10 = 40 
  INTEGER, PARAMETER :: ind_O = 41 
  INTEGER, PARAMETER :: ind_NO2 = 42 
  INTEGER, PARAMETER :: ind_OH = 43 
  INTEGER, PARAMETER :: ind_HO2 = 44 
  INTEGER, PARAMETER :: ind_O3 = 45 
  INTEGER, PARAMETER :: ind_NO3 = 46 
  INTEGER, PARAMETER :: ind_NO = 47 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_EMISS = 48 

! Index declaration for dummy species

  INTEGER, PARAMETER :: ind_O2 = 0 
  INTEGER, PARAMETER :: ind_NA = 0 
  INTEGER, PARAMETER :: ind_A = 0 
  INTEGER, PARAMETER :: ind_H = 0 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_EMISS = 1 

END MODULE model_Parameters

