! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : model_Monitor.f90
! Time                 : Sat Apr 22 13:43:50 2017
! Working directory    : /work/home/dp626/DSMACC-testing
! Equation file        : model.kpp
! Output root filename : model
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE model_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(29) :: SPC_NAMES = (/ &
     'DUMMY          ','SO3            ','CL             ', & ! index 1 - 3
     'CH4            ','O1D            ','HSO3           ', & ! index 4 - 6
     'CH3O2NO2       ','H2             ','N2O5           ', & ! index 7 - 9
     'H2O2           ','CH3OH          ','HONO           ', & ! index 10 - 12
     'CO             ','SO2            ','HO2NO2         ', & ! index 13 - 15
     'CH3O           ','CH3NO3         ','HNO3           ', & ! index 16 - 18
     'CH3OOH         ','HCHO           ','CH3O2          ', & ! index 19 - 21
     'NO3            ','O              ','OH             ', & ! index 22 - 24
     'NO2            ','NO             ','O3             ', & ! index 25 - 27
     'HO2            ','EMISS          ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '   CL + CH4 --> CH3O2                                                                               ', & ! index 1
     '   CH4 + OH --> CH3O2                                                                               ', & ! index 2
     'CH3O2 + HO2 --> CH3OOH                                                                              ', & ! index 3
     'CH3O2 + HO2 --> HCHO                                                                                ', & ! index 4
     ' CH3O2 + NO --> CH3NO3                                                                              ', & ! index 5
     ' CH3O2 + NO --> CH3O + NO2                                                                          ', & ! index 6
     'CH3O2 + NO2 --> CH3O2NO2                                                                            ', & ! index 7
     'CH3O2 + NO3 --> CH3O + NO2                                                                          ', & ! index 8
     '      CH3O2 --> CH3O                                                                                ', & ! index 9
     '      CH3O2 --> CH3OH                                                                               ', & ! index 10
     '      CH3O2 --> HCHO                                                                                ', & ! index 11
     '     CH3OOH --> CH3O + OH                                                                           ', & ! index 12
     'CH3OOH + OH --> CH3O2                                                                               ', & ! index 13
     'CH3OOH + OH --> HCHO + OH                                                                           ', & ! index 14
     '       HCHO --> CO + 2 HO2                                                                          ', & ! index 15
     '       HCHO --> H2 + CO                                                                             ', & ! index 16
     ' HCHO + NO3 --> CO + HNO3 + HO2                                                                     ', & ! index 17
     '  HCHO + OH --> CO + HO2                                                                            ', & ! index 18
     '     CH3NO3 --> CH3O + NO2                                                                          ', & ! index 19
     'CH3NO3 + OH --> HCHO + NO2                                                                          ', & ! index 20
     '       CH3O --> HCHO + HO2                                                                          ', & ! index 21
     '   CH3O2NO2 --> CH3O2 + NO2                                                                         ', & ! index 22
     ' CH3OH + OH --> HCHO + HO2                                                                          ', & ! index 23
     '          O --> O3                                                                                  ', & ! index 24
     '     O + O3 --> DUMMY                                                                               ', & ! index 25
     '     O + NO --> NO2                                                                                 ', & ! index 26
     '    O + NO2 --> NO                                                                                  ', & ! index 27
     '    O + NO2 --> NO3                                                                                 ', & ! index 28
     '        O1D --> O                                                                                   ', & ! index 29
     '    NO + O3 --> NO2                                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '   NO2 + O3 --> NO3                                                                                 ', & ! index 31
     '       2 NO --> 2 NO2                                                                               ', & ! index 32
     '   NO3 + NO --> 2 NO2                                                                               ', & ! index 33
     '  NO3 + NO2 --> NO2 + NO                                                                            ', & ! index 34
     '  NO3 + NO2 --> N2O5                                                                                ', & ! index 35
     '       N2O5 --> NO3 + NO2                                                                           ', & ! index 36
     '        O1D --> 2 OH                                                                                ', & ! index 37
     '    OH + O3 --> HO2                                                                                 ', & ! index 38
     '    H2 + OH --> HO2                                                                                 ', & ! index 39
     '    CO + OH --> HO2                                                                                 ', & ! index 40
     '  H2O2 + OH --> HO2                                                                                 ', & ! index 41
     '   O3 + HO2 --> OH                                                                                  ', & ! index 42
     '   OH + HO2 --> DUMMY                                                                               ', & ! index 43
     '      2 HO2 --> H2O2                                                                                ', & ! index 44
     '    OH + NO --> HONO                                                                                ', & ! index 45
     '   OH + NO2 --> HNO3                                                                                ', & ! index 46
     '   NO3 + OH --> NO2 + HO2                                                                           ', & ! index 47
     '   NO + HO2 --> OH + NO2                                                                            ', & ! index 48
     '  NO2 + HO2 --> HO2NO2                                                                              ', & ! index 49
     '     HO2NO2 --> NO2 + HO2                                                                           ', & ! index 50
     'HO2NO2 + OH --> NO2                                                                                 ', & ! index 51
     '  NO3 + HO2 --> OH + NO2                                                                            ', & ! index 52
     '  HONO + OH --> NO2                                                                                 ', & ! index 53
     '  HNO3 + OH --> NO3                                                                                 ', & ! index 54
     '    SO2 + O --> SO3                                                                                 ', & ! index 55
     '   SO2 + OH --> HSO3                                                                                ', & ! index 56
     '       HSO3 --> SO3 + HO2                                                                           ', & ! index 57
     '         O3 --> O1D                                                                                 ', & ! index 58
     '         O3 --> O                                                                                   ', & ! index 59
     '       H2O2 --> 2 OH                                                                                ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(7) :: EQN_NAMES_2 = (/ &
     '        NO2 --> O + NO                                                                              ', & ! index 61
     '        NO3 --> NO                                                                                  ', & ! index 62
     '        NO3 --> O + NO2                                                                             ', & ! index 63
     '       HONO --> OH + NO                                                                             ', & ! index 64
     '       HNO3 --> OH + NO2                                                                            ', & ! index 65
     '      DUMMY --> 0.5 DUMMY                                                                           ', & ! index 66
     '      EMISS --> EMISS                                                                               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(67) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2 /)

  CHARACTER(LEN=15), PARAMETER, DIMENSION(67) :: EQN_TAGS = (/ &
     '               ','               ','               ', & ! index 1 - 3
     '               ','               ','               ', & ! index 4 - 6
     '               ','               ','               ', & ! index 7 - 9
     '               ','               ','               ', & ! index 10 - 12
     '               ','               ','               ', & ! index 13 - 15
     '               ','               ','               ', & ! index 16 - 18
     '               ','               ','               ', & ! index 19 - 21
     '               ','               ','               ', & ! index 22 - 24
     '               ','               ','               ', & ! index 25 - 27
     '               ','               ','               ', & ! index 28 - 30
     '               ','               ','               ', & ! index 31 - 33
     '               ','               ','               ', & ! index 34 - 36
     '               ','               ','               ', & ! index 37 - 39
     '               ','               ','               ', & ! index 40 - 42
     '               ','               ','               ', & ! index 43 - 45
     '               ','               ','               ', & ! index 46 - 48
     '               ','               ','               ', & ! index 49 - 51
     '               ','               ','               ', & ! index 52 - 54
     '               ','               ','               ', & ! index 55 - 57
     '               ','               ','               ', & ! index 58 - 60
     '               ','               ','               ', & ! index 61 - 63
     '               ','               ','               ', & ! index 64 - 66
     '               ' /)

  CHARACTER(LEN=15), DIMENSION(1) :: FAM_NAMES
! INLINED global variables

! End INLINED global variables


END MODULE model_Monitor
