#PBS -N ZeroCool
#PBS -q x-large
### Merge output and error files
#PBS -j oe
#PBS -V
#PBS -l mem=300gb
#PBS -l nodes=1:ppn=64

#change to the directory that the command was issued from
cd $PBS_O_WORKDIR

export TMPDIR=/tmp/scratch
mkdir -p $TMPDIR

#PBS -e /tmp/scratch/$PBS_ARRAY_INDEX.e
#PBS -o /tmp/scratch/$PBS_ARRAY_INDEX.o

declare -i id
id=${PBS_ARRAY_INDEX}
echo ${id}
python z_multilayer_infomap.py lhs.h5 ${id}
